// 由 tools/build-terms.py 生成，不手改。审核台左栏的资料页树，以及配装的职业、类别与分支三张表。
window.starsidePages = [
  ["docs/rotation","轮换速查表","rotation/index.html","攻略与工具","","2026.8.30"],
  ["docs/ammo","弹药生成机制","ammo/index.html","机制","","2026.8.25"],
  ["docs/buff-debuffs","增伤 & 易伤","buff-debuffs/index.html","机制","","2026.8.30"],
  ["docs/combatant-scalars","战斗人员倍率","combatant-scalars/index.html","机制","","2026.8.14"],
  ["docs/game-mechanics","游戏机制","game-mechanics/index.html","机制","","2026.8.30"],
  ["docs/power-delta","压光伤害","power-delta/index.html","机制","","2026.8.14"],
  ["armor-sets","护甲套装效果","armor-sets/index.html","档案","","2026.8.30"],
  ["artifact-mods","神器模组","artifact-mods/index.html","档案","","2026.8.10"],
  ["docs/ability-cooldown","技能冷却","ability-cooldown/index.html","档案","","2026.8.25"],
  ["docs/armor-mods","护甲模组","armor-mods/index.html","档案","","2026.8.30"],
  ["docs/boss-hp","首领生命值","boss-hp/index.html","档案","","2026.8.30"],
  ["docs/elements","职业分支详解","elements/index.html","档案","","2026.8.23"],
  ["docs/exotic-armor","异域护甲详解","exotic-armor/index.html","档案","","2026.8.30"],
  ["docs/exotic-weapon","异域武器详解","exotic-weapon/index.html","档案","","2026.8.30"],
  ["docs/weapon-frames","武器框架","weapon-frames/index.html","档案","","2026.8.22"],
  ["docs/weapon-perks","武器 PERK 详解","weapon-perks/index.html","档案","","2026.8.30"],
  ["docs/arc","电弧","elements/arc/index.html","档案","docs/elements","2026.8.30"],
  ["docs/class-abilities","职业技能","elements/class-abilities/index.html","档案","docs/elements","2026.8.19"],
  ["docs/prismatic","棱镜","elements/prismatic/index.html","档案","docs/elements","2026.8.30"],
  ["docs/solar","烈日","elements/solar/index.html","档案","docs/elements","2026.8.30"],
  ["docs/stasis","冰影","elements/stasis/index.html","档案","docs/elements","2026.8.30"],
  ["docs/strand","缚丝","elements/strand/index.html","档案","docs/elements","2026.8.10"],
  ["docs/void","虚空","elements/void/index.html","档案","docs/elements","2026.8.30"],
  ["docs/changelog","更新日志","changelog/index.html","站务","","2026.8.30"],
  ["docs/palette","配色总览","palette/index.html","站务","","2026.8.24"],
  ["docs/sources","数据源与鸣谢","sources/index.html","站务","","2026.8.28"],
  ["docs/dps","DPS 排行","dps/index.html","终局分析","","2026.8.25"],
  ["docs/pve-farming","PVE 终局刷取指南","pve-farming/index.html","终局分析","","2026.8.30"],
  ["docs/raid-guides","Raid 攻略","raid-guides/index.html","终局分析","","2026.8.30"],
  ["docs/skill-damage","技能伤害排行","skill-damage/index.html","终局分析","","2026.8.30"],
  ["docs/swap-dps","切枪 DPS 排行","swap-dps/index.html","终局分析","","2026.8.30"],
  ["docs/crafting","锻造武器来源","crafting/index.html","终局分析","docs/pve-farming","2026.8.30"],
  ["docs/exotic-weapons","刷取清单-异域武器","exotic-weapons/index.html","终局分析","docs/pve-farming","2026.8.30"],
  ["docs/legendary-heavy","刷取清单-威能紫枪","legendary-heavy/index.html","终局分析","docs/pve-farming","2026.8.30"],
  ["docs/legendary-primary","刷取清单-白弹紫枪","legendary-primary/index.html","终局分析","docs/pve-farming","2026.8.30"],
  ["docs/legendary-special","刷取清单-绿弹紫枪","legendary-special/index.html","终局分析","docs/pve-farming","2026.8.30"],
  ["docs/shopping-heavy","购物清单-威能","shopping-heavy/index.html","终局分析","docs/pve-farming","2026.8.30"],
  ["docs/shopping-other","购物清单-其他","shopping-other/index.html","终局分析","docs/pve-farming","2026.8.30"],
  ["docs/shopping-primary","购物清单-白弹","shopping-primary/index.html","终局分析","docs/pve-farming","2026.8.30"],
  ["docs/shopping-special","购物清单-绿弹","shopping-special/index.html","终局分析","docs/pve-farming","2026.8.30"],
]
window.starsideBuilds = {"classes":["猎人","泰坦","术士"],"cats":["meta","强度","创意","PVP"],"branch":{"电弧":"arc","烈日":"solar","虚空":"void","冰影":"stasis","缚丝":"strand","棱镜":"prismatic"}}
