// 由 tools/build-terms.py 生成，不手改。改词表改 check_terms.TERMS 或 tools/items.json。
window.starsideTerms = {
terms: [
  ["填装",null,["装填"]],
  ["传说",null,["传奇"]],
  ["回复倍率",null,["技能块"]],
  ["疲惫",null,["力竭"]],
  ["起源特性",null,["源头特性","起源 Perk"]],
  ["终结技","enemy",[]],
  ["冰霜护甲","el-stasis",["冰霜铠甲"]],
  ["红血","bar-red",["杂兵","普通士兵","普通敌人","普通战斗人员"]],
  ["橙血","bar-orange",["精英"]],
  ["初级首领","bar-yellow",["黄血","小头目"]],
  ["战斗人员","enemy",["敌人"]],
  ["威能弹药","ammo-heavy",["重型弹药"]],
  ["虚弱","deb-void",["削弱"]],
  ["震颤","deb-arc",["感电"]],
  ["精准命中","stack",["精密命中"]],
  ["精准击杀",null,["精密击杀"]],
  ["直击伤害",null,["接触伤害"]],
  ["势不可挡勇士","enemy",["不屈勇士"]],
  ["过载勇士","enemy",["超载勇士"]],
  ["屏障勇士","enemy",["壁垒勇士"]],
  ["特技闪身",null,["杂技闪身"]],
  ["裂痕",null,["裂缝"]],
  ["护甲充能","armor-charge",[]],
  ["焕光","el-solar",[]],
  ["恢复","el-solar",[]],
  ["虚空覆盖护盾","el-void",[]],
  ["覆盖护盾","pickup",[]],
  ["不稳定","deb-void",[]],
  ["压制","deb-void",[]],
  ["减速","deb-stasis",[]],
  ["灼烧","deb-solar",[]],
  ["点燃","deb-solar",[]],
  ["能量球","orb",[]],
  ["特殊弹药","ammo-special",[]],
  ["生命值","health",[]],
  ["首领","bar-yellow",["头目","Boss","boss"]],
  ["守护者","bar-orange",[]],
  ["自己","enemy",[]],
  ["施法者","enemy",[]],
  ["异域","exotic",[]],
  ["增益","buff",[]],
  ["减益","debuff",[]],
  ["烈焰火苗",null,["鬼火","幽灵手雷"]],
  ["束缚",null,["系缚"]],
  ["狂啸",null,["暴风雪"]],
  ["击败他们",null,["击倒"]],
  ["速度加成",null,["速度助推器","速度增强"]],
  ["力量学派",null,["力量教派"]],
  ["洞察学派",null,["洞察教派"]],
  ["活力学派",null,["活力教派"]],
  ["忧愁武器",null,["悲叹武器"]],
  ["太阳黑子",null,["日斑"]],
  ["恢复炮台",null,["治疗炮台","治疗炮塔"]],
  ["虚空灵魂",null,["虚空之魂"]],
  ["高贵追踪弹",null,["高尚追踪弹"]],
  ["纳米蜂群",null,["纳米机器人","水银纳米机器"]],
  ["类虫机器人",null,["昆虫机器人"]],
  ["闪烁重击",null,["瞬移重击"]],
  ["遥测规律",null,["遥测模块"]],
  ["压迫能量",null,["压倒性力量"]],
  ["释放力量",null,["释放能量"]],
  ["蜕变圆球",null,["蜕变球体"]],
  ["活性放射体液",null,["放射虫液","放射虫池"]],
  ["先锋决心",null,["先锋决绝"]],
  ["斥候步枪",null,["侦察步枪"]],
  ["眩晕",null,["击晕"]],
  ["迷失方向",null,["迷乱"]],
  ["风暴怒吼","el-stasis",["冰川咆哮"]],
  ["区域拒止",null,["区域拒绝"]],
  ["重伤",null,["濒死生命值","危急","关键{health|生命值}"]],
  ["灼烧","deb-solar",["焦灼"]],
  ["残余",null,["残存"]],
  ["玻璃拱顶",null,["玻璃宝库"]],
  ["救赎的边缘",null,["救赎边缘"]],
  ["众神殿",null,["万神殿"]],
  ["幽梦之城",null,["梦城"]],
  ["铁旗",null,["铁骑"]],
  ["赛雀联赛",null,["快雀竞赛","快雀竞速"]],
  ["忧伤祭坛",null,["月球祭坛"]],
  ["异端深渊",null,["异端深坑"]],
  ["永恒沙漠（史诗）",null,["史诗沙漠"]],
  ["至日",null,["高塔二至点"]],
  ["守护者游戏",null,["高塔运动会"]],
  ["克洛塔的末日",null,["克洛塔末日"]],
  ["仄",null,["老九"]],
],
tokens: {
  "ammo-heavy": "ammo-heavy",
  "ammo-special": "ammo-special",
  "armor-charge": "armor-charge",
  "art-perk": "c-artifact",
  "bar-orange": "c-bar-orange",
  "bar-red": "c-bar-red",
  "bar-yellow": "c-bar-yellow",
  "buff": "buff",
  "deb-arc": "deb-arc",
  "deb-solar": "deb-solar",
  "deb-stasis": "deb-stasis",
  "deb-strand": "deb-strand",
  "deb-void": "deb-void",
  "debuff": "debuff",
  "el-arc": "el-arc",
  "el-kinetic": "el-kinetic",
  "el-prismatic": "el-prismatic",
  "el-solar": "el-solar",
  "el-stasis": "el-stasis",
  "el-strand": "el-strand",
  "el-void": "el-void",
  "enemy": "enemy",
  "exotic": "exotic",
  "health": "health",
  "kind": "kind",
  "note": "note",
  "orb": "orb",
  "perk": "c-perk",
  "pickup": "pickup",
  "pvp": "pvp",
  "stack": "stack",
  "unsure": "unsure",
},
classes: ["ammo-heavy","ammo-special","armor-charge","art-perk","artifact","b-arc","b-prismatic","b-solar","b-stasis","b-strand","b-void","bar-orange","bar-red","bar-yellow","block","buff","by","c1","c2","c3","c4","cat","chip","chip-break","circle","cn","core","d1","d2","d3","deb-arc","deb-solar","deb-stasis","deb-strand","deb-void","debuff","default","el-arc","el-kinetic","el-prismatic","el-solar","el-stasis","el-strand","el-void","enemy","entries","entry","entry-by","entry-kind","entry-meta","entry-node","entry-stamp","exotic","g","g-a","g-b","g-c","g-d","g-e","g-f","g-s","g1","g2","g3","gen","grid-flow","group-label","head-row","health","hero","hero-band","hero-mark","hero-note","hero-search","hero-sub","hero-util","hit","hit-at","hit-x","hits","hits-more","home","hunter","index","is-in","kind","l1","l2","l3","l4","lane","lead","legal","line","mark","na","note","on","orb","orbit","page-head","perk","pickup","pl-art","pl-say","pledge","pvp","pvp-eg","qq","r1","r2","r3","rays","rhombi","ring","s1","s2","s3","s4","s5","s6","sect-label","sep","shape","shapes","site-foot","site-head","site-nav","stack","stamp","step","sup-cell","support","titan","tool-chips","tool-count","tool-search","toolbar","unsure","warlock","wide","woff2","wordmark","wordmark-meta","wordmark-row"],
pageClasses: {
  "artifact-mods": ["art-bar","art-emblem","art-head","art-tags","emblem","intro","lede","mod","mod-desc","mod-icon","mod-row","notice","notice-body","tier-head","tier-rail"],
  "builds/s29-凯旋纪念碑/16gnj6n4-warlock": ["art","bn","build-head","build-id","by-label","cells","cls","cls-id","copy","desc","dp-body","dp-name","dpanel","empty","entry-foot","facet-label","facets","gear","gl","gl-img","gun","head-acts","hint","id-row","item","kd","like","likes","move","new-link","nm","node","pair","pc","perk-cell","picker","picker-bar","picker-grid","preview","rig","season","set","slot","slot-count","slot-row","slot-tool","src-block","src-tools","stat","stat-num","stat-picker","stats","stats-card","sub","sub-label","tags","tagset","tool-facet","v","val","who","who-in"],
  "builds/s29-凯旋纪念碑/4kyzrz0z-hunter": ["art","bn","build-head","build-id","by-label","cells","cls","cls-id","copy","desc","dp-body","dp-name","dpanel","empty","entry-foot","facet-label","facets","gear","gl","gl-img","gun","head-acts","hint","id-row","item","kd","like","likes","move","new-link","nm","node","pair","pc","perk-cell","picker","picker-bar","picker-grid","preview","rig","season","set","slot","slot-count","slot-row","slot-tool","src-block","src-tools","stat","stat-num","stat-picker","stats","stats-card","sub","sub-label","tags","tagset","tool-facet","v","val","who","who-in"],
  "builds/s29-凯旋纪念碑/9yfchje1-warlock": ["art","bn","build-head","build-id","by-label","cells","cls","cls-id","copy","desc","dp-body","dp-name","dpanel","empty","entry-foot","facet-label","facets","gear","gl","gl-img","gun","head-acts","hint","id-row","item","kd","like","likes","move","new-link","nm","node","pair","pc","perk-cell","picker","picker-bar","picker-grid","preview","rig","season","set","slot","slot-count","slot-row","slot-tool","src-block","src-tools","stat","stat-num","stat-picker","stats","stats-card","sub","sub-label","tags","tagset","tool-facet","v","val","who","who-in"],
  "builds/s29-凯旋纪念碑/acdzuqsl-warlock": ["art","bn","build-head","build-id","by-label","cells","cls","cls-id","copy","desc","dp-body","dp-name","dpanel","empty","entry-foot","facet-label","facets","gear","gl","gl-img","gun","head-acts","hint","id-row","item","kd","like","likes","move","new-link","nm","node","pair","pc","perk-cell","picker","picker-bar","picker-grid","preview","rig","season","set","slot","slot-count","slot-row","slot-tool","src-block","src-tools","stat","stat-num","stat-picker","stats","stats-card","sub","sub-label","tags","tagset","tool-facet","v","val","who","who-in"],
  "builds/s29-凯旋纪念碑/bxjyhdhm-titan": ["art","bn","build-head","build-id","by-label","cells","cls","cls-id","copy","desc","dp-body","dp-name","dpanel","empty","entry-foot","facet-label","facets","gear","gl","gl-img","gun","head-acts","hint","id-row","item","kd","like","likes","move","new-link","nm","node","pair","pc","perk-cell","picker","picker-bar","picker-grid","preview","rig","season","set","slot","slot-count","slot-row","slot-tool","src-block","src-tools","stat","stat-num","stat-picker","stats","stats-card","sub","sub-label","tags","tagset","tool-facet","v","val","who","who-in"],
  "builds/s29-凯旋纪念碑/clama-he-titan": ["art","bn","build-head","build-id","by-label","cells","cls","cls-id","copy","desc","dp-body","dp-name","dpanel","empty","entry-foot","facet-label","facets","gear","gl","gl-img","gun","head-acts","hint","id-row","item","kd","like","likes","move","new-link","nm","node","pair","pc","perk-cell","picker","picker-bar","picker-grid","preview","rig","season","set","slot","slot-count","slot-row","slot-tool","src-block","src-tools","stat","stat-num","stat-picker","stats","stats-card","sub","sub-label","tags","tagset","tool-facet","v","val","who","who-in"],
  "builds/s29-凯旋纪念碑/haku-solarjizhi-warlock": ["art","bn","build-head","build-id","by-label","cells","cls","cls-id","copy","desc","dp-body","dp-name","dpanel","empty","entry-foot","facet-label","facets","gear","gl","gl-img","gun","head-acts","hint","id-row","item","kd","like","likes","move","new-link","nm","node","pair","pc","perk-cell","picker","picker-bar","picker-grid","preview","rig","season","set","slot","slot-count","slot-row","slot-tool","src-block","src-tools","stat","stat-num","stat-picker","stats","stats-card","sub","sub-label","tags","tagset","tool-facet","v","val","who","who-in"],
  "builds/s29-凯旋纪念碑/iuhsh3n7-warlock": ["art","bn","build-head","build-id","by-label","cells","cls","cls-id","copy","desc","dp-body","dp-name","dpanel","empty","entry-foot","facet-label","facets","gear","gl","gl-img","gun","head-acts","hint","id-row","item","kd","like","likes","move","new-link","nm","node","pair","pc","perk-cell","picker","picker-bar","picker-grid","preview","rig","season","set","slot","slot-count","slot-row","slot-tool","src-block","src-tools","stat","stat-num","stat-picker","stats","stats-card","sub","sub-label","tags","tagset","tool-facet","v","val","who","who-in"],
  "builds/s29-凯旋纪念碑/jianqi-fengbao-warlock": ["art","bn","build-head","build-id","by-label","cells","cls","cls-id","copy","desc","dp-body","dp-name","dpanel","empty","entry-foot","facet-label","facets","gear","gl","gl-img","gun","head-acts","hint","id-row","item","kd","like","likes","move","new-link","nm","node","pair","pc","perk-cell","picker","picker-bar","picker-grid","preview","rig","season","set","slot","slot-count","slot-row","slot-tool","src-block","src-tools","stat","stat-num","stat-picker","stats","stats-card","sub","sub-label","tags","tagset","tool-facet","v","val","who","who-in"],
  "builds/s29-凯旋纪念碑/jianqi-kongjufusi-warlock": ["art","bn","build-head","build-id","by-label","cells","cls","cls-id","copy","desc","dp-body","dp-name","dpanel","empty","entry-foot","facet-label","facets","gear","gl","gl-img","gun","head-acts","hint","id-row","item","kd","like","likes","move","new-link","nm","node","pair","pc","perk-cell","picker","picker-bar","picker-grid","preview","rig","season","set","slot","slot-count","slot-row","slot-tool","src-block","src-tools","stat","stat-num","stat-picker","stats","stats-card","sub","sub-label","tags","tagset","tool-facet","v","val","who","who-in"],
  "builds/s29-凯旋纪念碑/jianqi-shuangpaoyi-warlock": ["art","bn","build-head","build-id","by-label","cells","cls","cls-id","copy","desc","dp-body","dp-name","dpanel","empty","entry-foot","facet-label","facets","gear","gl","gl-img","gun","head-acts","hint","id-row","item","kd","like","likes","move","new-link","nm","node","pair","pc","perk-cell","picker","picker-bar","picker-grid","preview","rig","season","set","slot","slot-count","slot-row","slot-tool","src-block","src-tools","stat","stat-num","stat-picker","stats","stats-card","sub","sub-label","tags","tagset","tool-facet","v","val","who","who-in"],
  "builds/s29-凯旋纪念碑/kvy77e2g-titan": ["art","bn","build-head","build-id","by-label","cells","cls","cls-id","copy","desc","dp-body","dp-name","dpanel","empty","entry-foot","facet-label","facets","gear","gl","gl-img","gun","head-acts","hint","id-row","item","kd","like","likes","move","new-link","nm","node","pair","pc","perk-cell","picker","picker-bar","picker-grid","preview","rig","season","set","slot","slot-count","slot-row","slot-tool","src-block","src-tools","stat","stat-num","stat-picker","stats","stats-card","sub","sub-label","tags","tagset","tool-facet","v","val","who","who-in"],
  "builds/s29-凯旋纪念碑/madoka-yuansudashi-hunter": ["art","bn","build-head","build-id","by-label","cells","cls","cls-id","copy","desc","dp-body","dp-name","dpanel","empty","entry-foot","facet-label","facets","gear","gl","gl-img","gun","head-acts","hint","id-row","item","kd","like","likes","move","new-link","nm","node","pair","pc","perk-cell","picker","picker-bar","picker-grid","preview","rig","season","set","slot","slot-count","slot-row","slot-tool","src-block","src-tools","stat","stat-num","stat-picker","stats","stats-card","sub","sub-label","tags","tagset","tool-facet","v","val","who","who-in"],
  "builds/s29-凯旋纪念碑/mengdong-hechengstasis-titan": ["art","bn","build-head","build-id","by-label","cells","cls","cls-id","copy","desc","dp-body","dp-name","dpanel","empty","entry-foot","facet-label","facets","gear","gl","gl-img","gun","head-acts","hint","id-row","item","kd","like","likes","move","new-link","nm","node","pair","pc","perk-cell","picker","picker-bar","picker-grid","preview","rig","season","set","slot","slot-count","slot-row","slot-tool","src-block","src-tools","stat","stat-num","stat-picker","stats","stats-card","sub","sub-label","tags","tagset","tool-facet","v","val","who","who-in"],
  "builds/s29-凯旋纪念碑/mkguedf2-hunter": ["art","bn","build-head","build-id","by-label","cells","cls","cls-id","copy","desc","dp-body","dp-name","dpanel","empty","entry-foot","facet-label","facets","gear","gl","gl-img","gun","head-acts","hint","id-row","item","kd","like","likes","move","new-link","nm","node","pair","pc","perk-cell","picker","picker-bar","picker-grid","preview","rig","season","set","slot","slot-count","slot-row","slot-tool","src-block","src-tools","stat","stat-num","stat-picker","stats","stats-card","sub","sub-label","tags","tagset","tool-facet","v","val","who","who-in"],
  "builds/s29-凯旋纪念碑/niangaoming-hexieqingping-warlock": ["art","bn","build-head","build-id","by-label","cells","cls","cls-id","copy","desc","dp-body","dp-name","dpanel","empty","entry-foot","facet-label","facets","gear","gl","gl-img","gun","head-acts","hint","id-row","item","kd","like","likes","move","new-link","nm","node","pair","pc","perk-cell","picker","picker-bar","picker-grid","preview","rig","season","set","slot","slot-count","slot-row","slot-tool","src-block","src-tools","stat","stat-num","stat-picker","stats","stats-card","sub","sub-label","tags","tagset","tool-facet","v","val","who","who-in"],
  "builds/s29-凯旋纪念碑/nianqingren-hexiaodi-hunter": ["art","bn","build-head","build-id","by-label","cells","cls","cls-id","copy","desc","dp-body","dp-name","dpanel","empty","entry-foot","facet-label","facets","gear","gl","gl-img","gun","head-acts","hint","id-row","item","kd","like","likes","move","new-link","nm","node","pair","pc","perk-cell","picker","picker-bar","picker-grid","preview","rig","season","set","slot","slot-count","slot-row","slot-tool","src-block","src-tools","stat","stat-num","stat-picker","stats","stats-card","sub","sub-label","tags","tagset","tool-facet","v","val","who","who-in"],
  "builds/s29-凯旋纪念碑/nightcore-baolei-hunter": ["art","bn","build-head","build-id","by-label","cells","cls","cls-id","copy","desc","dp-body","dp-name","dpanel","empty","entry-foot","facet-label","facets","gear","gl","gl-img","gun","head-acts","hint","id-row","item","kd","like","likes","move","new-link","nm","node","pair","pc","perk-cell","picker","picker-bar","picker-grid","preview","rig","season","set","slot","slot-count","slot-row","slot-tool","src-block","src-tools","stat","stat-num","stat-picker","stats","stats-card","sub","sub-label","tags","tagset","tool-facet","v","val","who","who-in"],
  "builds/s29-凯旋纪念碑/nightcore-swxsjz-hunter": ["art","bn","build-head","build-id","by-label","cells","cls","cls-id","copy","desc","dp-body","dp-name","dpanel","empty","entry-foot","facet-label","facets","gear","gl","gl-img","gun","head-acts","hint","id-row","item","kd","like","likes","move","new-link","nm","node","pair","pc","perk-cell","picker","picker-bar","picker-grid","preview","rig","season","set","slot","slot-count","slot-row","slot-tool","src-block","src-tools","stat","stat-num","stat-picker","stats","stats-card","sub","sub-label","tags","tagset","tool-facet","v","val","who","who-in"],
  "builds/s29-凯旋纪念碑/pkz20gm1-warlock": ["art","bn","build-head","build-id","by-label","cells","cls","cls-id","copy","desc","dp-body","dp-name","dpanel","empty","entry-foot","facet-label","facets","gear","gl","gl-img","gun","head-acts","hint","id-row","item","kd","like","likes","move","new-link","nm","node","pair","pc","perk-cell","picker","picker-bar","picker-grid","preview","rig","season","set","slot","slot-count","slot-row","slot-tool","src-block","src-tools","stat","stat-num","stat-picker","stats","stats-card","sub","sub-label","tags","tagset","tool-facet","v","val","who","who-in"],
  "builds/s29-凯旋纪念碑/qz9gs029-warlock": ["art","bn","build-head","build-id","by-label","cells","cls","cls-id","copy","desc","dp-body","dp-name","dpanel","empty","entry-foot","facet-label","facets","gear","gl","gl-img","gun","head-acts","hint","id-row","item","kd","like","likes","move","new-link","nm","node","pair","pc","perk-cell","picker","picker-bar","picker-grid","preview","rig","season","set","slot","slot-count","slot-row","slot-tool","src-block","src-tools","stat","stat-num","stat-picker","stats","stats-card","sub","sub-label","tags","tagset","tool-facet","v","val","who","who-in"],
  "builds/s29-凯旋纪念碑/tniihk60-warlock": ["art","bn","build-head","build-id","by-label","cells","cls","cls-id","copy","desc","dp-body","dp-name","dpanel","empty","entry-foot","facet-label","facets","gear","gl","gl-img","gun","head-acts","hint","id-row","item","kd","like","likes","move","new-link","nm","node","pair","pc","perk-cell","picker","picker-bar","picker-grid","preview","rig","season","set","slot","slot-count","slot-row","slot-tool","src-block","src-tools","stat","stat-num","stat-picker","stats","stats-card","sub","sub-label","tags","tagset","tool-facet","v","val","who","who-in"],
  "builds/s29-凯旋纪念碑/w0q7ss18-hunter": ["art","bn","build-head","build-id","by-label","cells","cls","cls-id","copy","desc","dp-body","dp-name","dpanel","empty","entry-foot","facet-label","facets","gear","gl","gl-img","gun","head-acts","hint","id-row","item","kd","like","likes","move","new-link","nm","node","pair","pc","perk-cell","picker","picker-bar","picker-grid","preview","rig","season","set","slot","slot-count","slot-row","slot-tool","src-block","src-tools","stat","stat-num","stat-picker","stats","stats-card","sub","sub-label","tags","tagset","tool-facet","v","val","who","who-in"],
  "builds/s29-凯旋纪念碑/xiaoning-xukongpvp-hunter": ["art","bn","build-head","build-id","by-label","cells","cls","cls-id","copy","desc","dp-body","dp-name","dpanel","empty","entry-foot","facet-label","facets","gear","gl","gl-img","gun","head-acts","hint","id-row","item","kd","like","likes","move","new-link","nm","node","pair","pc","perk-cell","picker","picker-bar","picker-grid","preview","rig","season","set","slot","slot-count","slot-row","slot-tool","src-block","src-tools","stat","stat-num","stat-picker","stats","stats-card","sub","sub-label","tags","tagset","tool-facet","v","val","who","who-in"],
  "builds/s29-凯旋纪念碑/xukonvoid-xinghuo-warlock": ["art","bn","build-head","build-id","by-label","cells","cls","cls-id","copy","desc","dp-body","dp-name","dpanel","empty","entry-foot","facet-label","facets","gear","gl","gl-img","gun","head-acts","hint","id-row","item","kd","like","likes","move","new-link","nm","node","pair","pc","perk-cell","picker","picker-bar","picker-grid","preview","rig","season","set","slot","slot-count","slot-row","slot-tool","src-block","src-tools","stat","stat-num","stat-picker","stats","stats-card","sub","sub-label","tags","tagset","tool-facet","v","val","who","who-in"],
  "builds/s29-凯旋纪念碑/yester-bguipen-titan": ["art","bn","build-head","build-id","by-label","cells","cls","cls-id","copy","desc","dp-body","dp-name","dpanel","empty","entry-foot","facet-label","facets","gear","gl","gl-img","gun","head-acts","hint","id-row","item","kd","like","likes","move","new-link","nm","node","pair","pc","perk-cell","picker","picker-bar","picker-grid","preview","rig","season","set","slot","slot-count","slot-row","slot-tool","src-block","src-tools","stat","stat-num","stat-picker","stats","stats-card","sub","sub-label","tags","tagset","tool-facet","v","val","who","who-in"],
  "builds/s29-凯旋纪念碑/yester-guidao-hunter": ["art","bn","build-head","build-id","by-label","cells","cls","cls-id","copy","desc","dp-body","dp-name","dpanel","empty","entry-foot","facet-label","facets","gear","gl","gl-img","gun","head-acts","hint","id-row","item","kd","like","likes","move","new-link","nm","node","pair","pc","perk-cell","picker","picker-bar","picker-grid","preview","rig","season","set","slot","slot-count","slot-row","slot-tool","src-block","src-tools","stat","stat-num","stat-picker","stats","stats-card","sub","sub-label","tags","tagset","tool-facet","v","val","who","who-in"],
  "builds/s29-凯旋纪念碑/yester-jtys-warlock": ["art","bn","build-head","build-id","by-label","cells","cls","cls-id","copy","desc","dp-body","dp-name","dpanel","empty","entry-foot","facet-label","facets","gear","gl","gl-img","gun","head-acts","hint","id-row","item","kd","like","likes","move","new-link","nm","node","pair","pc","perk-cell","picker","picker-bar","picker-grid","preview","rig","season","set","slot","slot-count","slot-row","slot-tool","src-block","src-tools","stat","stat-num","stat-picker","stats","stats-card","sub","sub-label","tags","tagset","tool-facet","v","val","who","who-in"],
  "builds/s29-凯旋纪念碑/yester-rendongdiudiu-hunter": ["art","bn","build-head","build-id","by-label","cells","cls","cls-id","copy","desc","dp-body","dp-name","dpanel","empty","entry-foot","facet-label","facets","gear","gl","gl-img","gun","head-acts","hint","id-row","item","kd","like","likes","move","new-link","nm","node","pair","pc","perk-cell","picker","picker-bar","picker-grid","preview","rig","season","set","slot","slot-count","slot-row","slot-tool","src-block","src-tools","stat","stat-num","stat-picker","stats","stats-card","sub","sub-label","tags","tagset","tool-facet","v","val","who","who-in"],
  "builds/s29-凯旋纪念碑/yester-xukongjiansheng-titan": ["art","bn","build-head","build-id","by-label","cells","cls","cls-id","copy","desc","dp-body","dp-name","dpanel","empty","entry-foot","facet-label","facets","gear","gl","gl-img","gun","head-acts","hint","id-row","item","kd","like","likes","move","new-link","nm","node","pair","pc","perk-cell","picker","picker-bar","picker-grid","preview","rig","season","set","slot","slot-count","slot-row","slot-tool","src-block","src-tools","stat","stat-num","stat-picker","stats","stats-card","sub","sub-label","tags","tagset","tool-facet","v","val","who","who-in"],
  "builds/s29-凯旋纪念碑/yiwangmelt-ggggdamage-hunter": ["art","bn","build-head","build-id","by-label","cells","cls","cls-id","copy","desc","dp-body","dp-name","dpanel","empty","entry-foot","facet-label","facets","gear","gl","gl-img","gun","head-acts","hint","id-row","item","kd","like","likes","move","new-link","nm","node","pair","pc","perk-cell","picker","picker-bar","picker-grid","preview","rig","season","set","slot","slot-count","slot-row","slot-tool","src-block","src-tools","stat","stat-num","stat-picker","stats","stats-card","sub","sub-label","tags","tagset","tool-facet","v","val","who","who-in"],
  "builds/s29-凯旋纪念碑/yiwangmelt-shoudian-hunter": ["art","bn","build-head","build-id","by-label","cells","cls","cls-id","copy","desc","dp-body","dp-name","dpanel","empty","entry-foot","facet-label","facets","gear","gl","gl-img","gun","head-acts","hint","id-row","item","kd","like","likes","move","new-link","nm","node","pair","pc","perk-cell","picker","picker-bar","picker-grid","preview","rig","season","set","slot","slot-count","slot-row","slot-tool","src-block","src-tools","stat","stat-num","stat-picker","stats","stats-card","sub","sub-label","tags","tagset","tool-facet","v","val","who","who-in"],
  "builds/s29-凯旋纪念碑/yiwangmelt-twjqg-hunter": ["art","bn","build-head","build-id","by-label","cells","cls","cls-id","copy","desc","dp-body","dp-name","dpanel","empty","entry-foot","facet-label","facets","gear","gl","gl-img","gun","head-acts","hint","id-row","item","kd","like","likes","move","new-link","nm","node","pair","pc","perk-cell","picker","picker-bar","picker-grid","preview","rig","season","set","slot","slot-count","slot-row","slot-tool","src-block","src-tools","stat","stat-num","stat-picker","stats","stats-card","sub","sub-label","tags","tagset","tool-facet","v","val","who","who-in"],
  "builds/s29-凯旋纪念碑/yiwangmelt-weiyiqingguai2-hunter": ["art","bn","build-head","build-id","by-label","cells","cls","cls-id","copy","desc","dp-body","dp-name","dpanel","empty","entry-foot","facet-label","facets","gear","gl","gl-img","gun","head-acts","hint","id-row","item","kd","like","likes","move","new-link","nm","node","pair","pc","perk-cell","picker","picker-bar","picker-grid","preview","rig","season","set","slot","slot-count","slot-row","slot-tool","src-block","src-tools","stat","stat-num","stat-picker","stats","stats-card","sub","sub-label","tags","tagset","tool-facet","v","val","who","who-in"],
  "builds/s29-凯旋纪念碑/ynwgmvks-warlock": ["art","bn","build-head","build-id","by-label","cells","cls","cls-id","copy","desc","dp-body","dp-name","dpanel","empty","entry-foot","facet-label","facets","gear","gl","gl-img","gun","head-acts","hint","id-row","item","kd","like","likes","move","new-link","nm","node","pair","pc","perk-cell","picker","picker-bar","picker-grid","preview","rig","season","set","slot","slot-count","slot-row","slot-tool","src-block","src-tools","stat","stat-num","stat-picker","stats","stats-card","sub","sub-label","tags","tagset","tool-facet","v","val","who","who-in"],
  "builds/s29-凯旋纪念碑/zqqoqjsb-warlock": ["art","bn","build-head","build-id","by-label","cells","cls","cls-id","copy","desc","dp-body","dp-name","dpanel","empty","entry-foot","facet-label","facets","gear","gl","gl-img","gun","head-acts","hint","id-row","item","kd","like","likes","move","new-link","nm","node","pair","pc","perk-cell","picker","picker-bar","picker-grid","preview","rig","season","set","slot","slot-count","slot-row","slot-tool","src-block","src-tools","stat","stat-num","stat-picker","stats","stats-card","sub","sub-label","tags","tagset","tool-facet","v","val","who","who-in"],
  "docs/ability-cooldown": ["den","formula","ico","lhs","num","var"],
  "docs/ammo": ["formula","from","rules"],
  "docs/arc": ["cd","ico","ico2","ico4","sk-arc","sk-solar","sk-stasis","sk-strand","sk-void","slot"],
  "docs/armor-mods": ["cost","ico"],
  "docs/boss-hp": ["amp","res"],
  "docs/buff-debuffs": ["ico","rules"],
  "docs/changelog": ["act","is-same"],
  "docs/class-abilities": ["cd","ico","ico2","ico4","sk-arc","sk-solar","sk-stasis","sk-strand","sk-void","slot"],
  "docs/combatant-scalars": ["named"],
  "docs/dps": ["ico","sim"],
  "docs/elements": ["cd","ico","ico2","ico4","sk-arc","sk-solar","sk-stasis","sk-strand","sk-void","slot"],
  "docs/exotic-armor": ["ico","spirit"],
  "docs/exotic-weapon": ["ico"],
  "docs/exotic-weapons": ["champ","ico"],
  "docs/game-mechanics": ["ico"],
  "docs/legendary-heavy": ["champ","ico","num","src"],
  "docs/legendary-primary": ["champ","ico","num","src"],
  "docs/legendary-special": ["champ","ico","num","src"],
  "docs/palette": ["amp","c-ammo","c-ammo-special","c-arc","c-artifact","c-bar-orange","c-bar-red","c-bar-yellow","c-buff","c-charge","c-debuff","c-enemy","c-exotic","c-health","c-kinetic","c-legend","c-note","c-orb","c-perk","c-prism","c-pvp","c-solar","c-stack","c-stasis","c-strand","c-term","c-unsure","c-void","cost","res","sim","sk-arc","sk-solar","sk-stasis","sk-strand","sk-void"],
  "docs/power-delta": ["axis","base","cap","chart","chart-legend","cursor","dot","grid","k","s0","tag","tick","ty"],
  "docs/prismatic": ["cd","ico","ico2","ico4","sk-arc","sk-solar","sk-stasis","sk-strand","sk-void","slot"],
  "docs/raid-guides": ["guide","guide-name","guide-shot","guide-tag","guides"],
  "docs/rotation": ["chain","is-mid","is-now","rota","rota-badge","rota-body","rota-btns","rota-card","rota-date","rota-group","rota-kind","rota-pill","rota-stage","rota-top"],
  "docs/shopping-heavy": ["champ","ico","num","src"],
  "docs/shopping-other": ["champ","ico","num","src"],
  "docs/shopping-primary": ["champ","ico","num","src"],
  "docs/shopping-special": ["champ","ico","num","src"],
  "docs/skill-damage": ["ico"],
  "docs/solar": ["cd","ico","ico2","ico4","sk-arc","sk-solar","sk-stasis","sk-strand","sk-void","slot"],
  "docs/stasis": ["cd","ico","ico2","ico4","sk-arc","sk-solar","sk-stasis","sk-strand","sk-void","slot"],
  "docs/strand": ["cd","ico","ico2","ico4","sk-arc","sk-solar","sk-stasis","sk-strand","sk-void","slot"],
  "docs/swap-dps": ["ico"],
  "docs/void": ["cd","ico","ico2","ico4","sk-arc","sk-solar","sk-stasis","sk-strand","sk-void","slot"],
  "docs/weapon-frames": ["cfg","rules"],
  "docs/weapon-perks": ["enh","ico","src"],
},
guard: ["千语魅痕","冻结计时","层数冻结","治愈裂痕","迷惑爆发","守护者游戏","动能震颤","震颤反馈","不稳定弹药","势不可挡射击"],
keep: ["削弱清敌","Destiny 2: Boss Damage","吞食裂缝","卡巴尔：焦灼大地","残存回声","结晶残花","重型弹药搜寻者","重型弹药斥候"],
g6: ["ability-cooldown","ammo","arc","armor-mods","boss-hp","buff-debuffs","class-abilities","combatant-scalars","crafting","dps","elements","exotic-armor","exotic-weapon","exotic-weapons","game-mechanics","legendary-heavy","legendary-primary","legendary-special","power-delta","prismatic","pve-farming","raid-guides","rotation","shopping-heavy","shopping-other","shopping-primary","shopping-special","skill-damage","solar","sources","stasis","strand","swap-dps","void","weapon-frames","weapon-perks"],
items: [
  ["淘金者\\\\F.A.T.S.（全自动）\\\\连锁反应\\\\↑财力雄厚\\\\↑危险区域","exotic","异域 Perk"],
  ["导线步枪\\\\射手瞄具／战斗瞄具\\\\腰射握把／光速拔枪\\\\↑回转弹药","exotic","异域 Perk"],
  ["猎人踪迹I–IV\\\\可制作Perk\\\\点射模式\\\\↑可制作改装","exotic","异域 Perk"],
  ["M1R分布矩阵I–IV\\\\永恒漏洞\\\\↑可塑造Perk","exotic","异域 Perk"],
  ["四维超正方体\\\\无尽刀剑格挡\\\\无倦利刃\\\\↑另一维度","exotic","异域 Perk"],
  ["正确抉择\\\\注意了，守护者\\\\边打边劫\\\\↑羸弱能量球","exotic","异域 Perk"],
  ["三生视觉\\\\基本法则\\\\可塑造Perk\\\\↑还治彼身","exotic","异域 Perk"],
  ["分裂决策\\\\超因果弹片\\\\↑治疗弹匣\\\\↑霜华窃取者","exotic","异域 Perk"],
  ["属性：不可判定\\\\属性：不可约简\\\\↑属性：不可避免","exotic","异域 Perk"],
  ["巨型寒冰偃月\\\\沉重刀锋\\\\庸人自扰\\\\↑霜华窃取者","exotic","异域 Perk"],
  ["王牌猎人\\\\利维坦之叹\\\\↑巨型箭袋\\\\↑弓手节奏²","exotic","异域 Perk"],
  ["眼观六路\\\\适应性重炮\\\\↑爆破分配器\\\\↑爆破专家","exotic","异域 Perk"],
  ["SUROS遗产\\\\可选Perk\\\\↑SUROS权势","exotic","异域 Perk"],
  ["三平面质量\\\\改装散热器\\\\合并弹药\\\\↑反常燃烧","exotic","异域 Perk"],
  ["灵魂灼烧\\\\灵魂锻铸\\\\毁灭利刃\\\\↑可选Perk","exotic","异域 Perk"],
  ["米达多功能\\\\米达软件包\\\\米达雷达\\\\↑重要情报","exotic","异域 Perk"],
  ["谐振激光\\\\超充电池\\\\↑羸弱能量球\\\\↑引爆光束","exotic","异域 Perk"],
  ["重击步枪\\\\帝国效忠者\\\\↑辉耀炽热\\\\↑燃烧野心","exotic","异域 Perk"],
  ["充能射击\\\\盾牌迷途\\\\↑逼入绝境\\\\↑辉耀炽热","exotic","异域 Perk"],
  ["凯德的复仇\\\\黄金弹药\\\\狙击兵\\\\↑幸运的一击","exotic","异域 Perk"],
  ["恶意触碰\\\\充斥凋零\\\\↑慈悲触碰\\\\↑精准工具","exotic","异域 Perk"],
  ["意外缓刑\\\\预兆脉动\\\\↑财力雄厚\\\\↑先知怒火","exotic","异域 Perk"],
  ["时间操控I–IV\\\\时间异常\\\\↑可塑造Perk","exotic","异域 Perk"],
  ["星光光束\\\\电弧校准\\\\相位转化器\\\\↑超充矩阵","exotic","异域 Perk"],
  ["颅骨之刺I–IV\\\\可制作Perk\\\\↑暗铸扳机","exotic","异域 Perk"],
  ["动如奔牛\\\\「Yeehaw」狂暴\\\\↑动如奔牛","exotic","异域 Perk"],
  ["原型真理探索者\\\\手雷与马蹄铁\\\\↑收割者贡品","exotic","异域 Perk"],
  ["女妖之嚎\\\\急速消耗\\\\无倦利刃\\\\↑燃烧野心","exotic","异域 Perk"],
  ["恐慌反应I–V\\\\傀儡分歧\\\\↑可制作Perk","exotic","异域 Perk"],
  ["激燃火焰\\\\腰射握把\\\\↑杀人风\\\\↑嫉妒刺客","exotic","异域 Perk"],
  ["睡美人\\\\移动目标\\\\↑加速线圈\\\\↑财力雄厚","exotic","异域 Perk"],
  ["织陷者I–IV\\\\缠丝杀手\\\\↑可制作Perk","exotic","异域 Perk"],
  ["超因果光束\\\\超因果注入\\\\↑阻止力\\\\↑敲打","exotic","异域 Perk"],
  ["透体电光\\\\千里眼\\\\↑财力雄厚\\\\↑战嚎炮管","exotic","异域 Perk"],
  ["乌鸦之翼\\\\决斗者之境\\\\无倦利刃\\\\↑逆转","exotic","异域 Perk"],
  ["光能聚集\\\\旅行者的赠礼\\\\↑渗透\\\\↑充盈","exotic","异域 Perk"],
  ["疯狂科学家\\\\机械自动填装\\\\↑精确制导模块","exotic","异域 Perk"],
  ["腐蚀扩散\\\\可制作Perk\\\\寄生\\\\↑病媒","exotic","异域 Perk"],
  ["蔓延羸弱\\\\什一收割\\\\↑洋底贡品\\\\↑墓碑","exotic","异域 Perk"],
  ["革命\\\\动态充能\\\\↑电弧冥河\\\\↑涡流电流","exotic","异域 Perk"],
  ["黑洞\\\\宇宙奥秘\\\\↑还治彼身\\\\↑斩首武器","exotic","异域 Perk"],
  ["夜誓之视I–IV\\\\穿心者\\\\↑可塑造改装","exotic","异域 Perk"],
  ["大师\\\\靶心加固\\\\速射瞄准\\\\↑顶阶精通","exotic","异域 Perk"],
  ["毁灭铭刻锻炉\\\\毁灭铭刻信标\\\\↑诱导推销","exotic","异域 Perk"],
  ["热毒子弹\\\\测距仪\\\\↑连锁反应\\\\↑狂暴","exotic","异域 Perk"],
  ["类虫机器人榴弹\\\\群居服务者\\\\↑财力雄厚","exotic","异域 Perk"],
  ["审判\\\\苦修\\\\↑聚焦狂怒\\\\↑震颤反馈","exotic","异域 Perk"],
  ["尖啸群击\\\\毒性过载\\\\↑枯骨鳞片催化剂","exotic","异域 Perk"],
  ["巨像之怒\\\\欧米伽打击\\\\↑大序曲催化剂","exotic","异域 Perk"],
  ["拉格朗日瞄具\\\\电磁异常\\\\↑跃迁驱动器","exotic","异域 Perk"],
  ["指引光环\\\\阿波罗切线\\\\↑泛光细分曲面","exotic","异域 Perk"],
  ["指挥框架\\\\狂热长矛\\\\↑可塑造Perk","exotic","异域 Perk"],
  ["蒙特卡洛法则\\\\马尔可夫链\\\\↑刺刀上膛","exotic","异域 Perk"],
  ["超因果射击\\\\随机Perk\\\\↑猎人之境","exotic","异域 Perk"],
  ["阿格尔的召唤\\\\雷加的叠句\\\\↑意志实体","exotic","异域 Perk"],
  ["吞噬者印记\\\\灵魂吞噬者\\\\↑精炼之魂","exotic","异域 Perk"],
  ["导弹追踪弹\\\\手雷追逐者\\\\↑纳米纠缠","exotic","异域 Perk"],
  ["收割者尖刺\\\\残余炼金术\\\\↑我为人人","exotic","异域 Perk"],
  ["月牙白\\\\可打造Perk\\\\↑轻声呼吸","exotic","异域 Perk"],
  ["蠕虫饥饿\\\\蠕虫副产品\\\\↑嫉妒军械库","exotic","异域 Perk"],
  ["阿罕卡拉之眼\\\\不测回响\\\\↑恩宠尽失","exotic","异域 Perk"],
  ["霰弹发射器\\\\狼群出动\\\\↑尖牙与利爪","exotic","异域 Perk"],
  ["LN2点射\\\\液态冷却\\\\↑冷冻效率","exotic","异域 Perk"],
  ["冰冻大炮\\\\碎裂射击\\\\↑霜华窃取者","exotic","异域 Perk"],
  ["古昧的折磨\\\\倾家荡产\\\\↑无声报警","exotic","异域 Perk"],
  ["复合推进剂\\\\高辛烷值\\\\↑烈焰术士","exotic","异域 Perk"],
  ["永恒揭秘者\\\\时间无限\\\\↑精算平衡","exotic","异域 Perk"],
  ["爆炸暗影\\\\傀儡捕食者\\\\↑斩首武器","exotic","异域 Perk"],
  ["腐化核合成\\\\忠诚飞蛾\\\\↑狂暴上头","exotic","异域 Perk"],
  ["重型投弹器\\\\巨人之甲\\\\↑军团壁垒","exotic","异域 Perk"],
  ["量子新星\\\\亚原子扭曲\\\\↑心无旁骛","exotic","异域 Perk"],
  ["闪电追踪弹\\\\震颤反馈\\\\↑涡流电流","exotic","异域 Perk"],
  ["防护编织\\\\纬纱切线手\\\\↑棘手绳结","exotic","异域 Perk"],
  ["不知悔改\\\\涉险而为\\\\↑狭窄视野","exotic","异域 Perk"],
  ["光弹发射器\\\\赶牛者\\\\↑辉耀炽热","exotic","异域 Perk"],
  ["再次回转\\\\喂食狂热\\\\↑侧翼爆击","exotic","异域 Perk"],
  ["冰雹弹幕\\\\冰雹风暴\\\\↑寒噤箭袋","exotic","异域 Perk"],
  ["冷酷融合\\\\漫长寒冬\\\\↑超充弹匣","exotic","异域 Perk"],
  ["动荡光芒\\\\基本法则\\\\↑光能之触","exotic","异域 Perk"],
  ["叛徒器皿\\\\狂风骤雨\\\\↑离子葬礼","exotic","异域 Perk"],
  ["基本法则\\\\离子回归\\\\↑盾牌迷途","exotic","异域 Perk"],
  ["女王之怒\\\\狩猎箭头\\\\↑我为人人","exotic","异域 Perk"],
  ["恢复炮台\\\\辉耀炽热\\\\↑治疗弹匣","exotic","异域 Perk"],
  ["掘尸三尺\\\\暗地一击\\\\↑幽魂漫步","exotic","异域 Perk"],
  ["棱镜炼狱\\\\烈焰回馈\\\\↑辉耀炽热","exotic","异域 Perk"],
  ["潜藏能量\\\\能量激涌\\\\↑虚空大师","exotic","异域 Perk"],
  ["烈日灼烧\\\\烈日爆炸\\\\↑顺畅换弹","exotic","异域 Perk"],
  ["狼群弹药\\\\集群猎人\\\\↑猛狼成群","exotic","异域 Perk"],
  ["电弧陷阱\\\\即兴弹药\\\\↑震颤反馈","exotic","异域 Perk"],
  ["砥砺刀锋\\\\心无旁骛\\\\↑无双刀锋","exotic","异域 Perk"],
  ["神圣之焰\\\\因果箭矢\\\\↑因果箭袋","exotic","异域 Perk"],
  ["禁用武器\\\\残忍疗法\\\\↑痛苦之道","exotic","异域 Perk"],
  ["私人助手\\\\目标锁定\\\\↑联网瞄准","exotic","异域 Perk"],
  ["精准弹头\\\\天生在途\\\\↑精准连击","exotic","异域 Perk"],
  ["统治浩劫\\\\闪电弹药\\\\↑闪击返还","exotic","异域 Perk"],
  ["致命极性\\\\风暴使者\\\\↑精准连击","exotic","异域 Perk"],
  ["虚空榨取\\\\本影食物\\\\↑冲击支撑","exotic","异域 Perk"],
  ["裂解弹药\\\\悬停爆破\\\\↑瓦解爆破","exotic","异域 Perk"],
  ["诅咒之绳\\\\腰射握把\\\\↑无尽诅咒","exotic","异域 Perk"],
  ["贪食野兽\\\\无尽食欲\\\\↑刺客野心","exotic","异域 Perk"],
  ["迅疾雷霆\\\\猛烈抨击\\\\↑名为死神","exotic","异域 Perk"],
  ["过充电容\\\\再生运动\\\\↑静电累积","exotic","异域 Perk"],
  ["迎头赶上\\\\火焰创世\\\\↑集体行动","exotic","异域 Perk"],
  ["远程护盾\\\\失衡弹药\\\\↑冲击支撑","exotic","异域 Perk"],
  ["飞空之牙\\\\俯冲利爪\\\\↑飞行怪物","exotic","异域 Perk"],
  ["饥渴弩箭\\\\暴力复活\\\\↑分脉血统","exotic","异域 Perk"],
  ["高尚弹药\\\\天空祝福\\\\↑美德回响","exotic","异域 Perk"],
  ["黑暗救赎\\\\黑暗后裔\\\\↑固定负载","exotic","异域 Perk"],
  ["一网打尽\\\\毒药抉择\\\\↑弦理论","exotic","异域 Perk"],
  ["冲击波\\\\科学方法\\\\↑财力雄厚","exotic","异域 Perk"],
  ["分裂电子\\\\避雷针\\\\↑叉状闪电","exotic","异域 Perk"],
  ["发薪日\\\\营业时间\\\\↑严肃生意","exotic","异域 Perk"],
  ["四头犬\\\\散射弹包\\\\↑集中火力","exotic","异域 Perk"],
  ["引燃扳机\\\\散热器\\\\↑瞬时热情","exotic","异域 Perk"],
  ["残酷真相\\\\殊死一搏\\\\↑大合奏","exotic","异域 Perk"],
  ["电弧导体\\\\超导体\\\\↑连锁反应","exotic","异域 Perk"],
  ["终有一死\\\\萤火虫\\\\↑丧礼葬火","exotic","异域 Perk"],
  ["远程武器\\\\鸬鹚反转\\\\鸬鹚连击","exotic","异域 Perk"],
  ["迟来满足\\\\物竞天择\\\\↑客迈拉","exotic","异域 Perk"],
  ["重金属\\\\十六进制\\\\↑目标锁定","exotic","异域 Perk"],
  ["两歧思维\\\\造义\\\\↑松散附着","exotic","异域 Perk"],
  ["冕冠巅峰\\\\预期\\\\↑充盈决心","exotic","异域 Perk"],
  ["到此为止\\\\收放自如\\\\↑巨岩","exotic","异域 Perk"],
  ["双尾\\\\戏耍猎物\\\\↑第三支尾","exotic","异域 Perk"],
  ["同谋\\\\疾风怒涛\\\\↑援助之手","exotic","异域 Perk"],
  ["圣人之拳\\\\突破\\\\↑光照无影","exotic","异域 Perk"],
  ["复合之力\\\\瓦解破裂\\\\↑创世","exotic","异域 Perk"],
  ["守恒动量\\\\刺激\\\\↑治疗弹匣","exotic","异域 Perk"],
  ["愚者宿命\\\\边打边劫\\\\萤火虫","exotic","异域 Perk"],
  ["救赎\\\\倒置关系\\\\↑援助之手","exotic","异域 Perk"],
  ["杀人目光\\\\一见即死\\\\↑慷慨","exotic","异域 Perk"],
  ["毒化箭矢\\\\速射瞄准\\\\↑不屈","exotic","异域 Perk"],
  ["诅咒使者\\\\绝望\\\\↑我为怨魂","exotic","异域 Perk"],
  ["无需背包\\\\破冰者\\\\↑破冰","exotic","异域 Perk"],
  ["纯五度\\\\禅意时刻\\\\↑蜻蜓","exotic","异域 Perk"],
  ["意外缓刑\\\\类虫机器人榴弹","exotic","异域 Perk"],
  ["松解\\\\纺锤\\\\↑启迪行动","exotic","异域 Perk"],
  ["鼠党\\\\鼠害\\\\↑隐患横行","exotic","异域 Perk"],
  ["超凡决斗者\\\\↑超凡钢铁","exotic","异域 Perk"],
  ["SLO-12开放式瞄具","perk","武器 Perk"],
  ["蜕变\\\\进化\\\\↑解构","exotic","异域 Perk"],
  ["过载后膛填装榴弹发射器","art-perk","传说 神器特性"],
  ["D.A.R.C.I.","exotic","异域 狙击步枪"],
  ["Omolon流体动力","perk","武器 Perk"],
  ["光能聚集\\\\狼群弹药","exotic","异域 Perk"],
  ["压缩枪膛\\\\黑翼之上","exotic","异域 Perk"],
  ["反屏障斥候和脉冲步枪","art-perk","传说 神器特性"],
  ["复苏指令\\\\纳米突袭","exotic","异域 Perk"],
  ["电弧导体\\\\风暴使者","exotic","异域 Perk"],
  ["神枪手光学瞄准镜：低","perk","武器 Perk"],
  ["神枪手光学瞄准镜：高","perk","武器 Perk"],
  ["赫沃斯托夫7G-0X","exotic","异域 自动步枪"],
  ["Häkke突入武装","perk","武器 Perk"],
  ["势不可挡手枪和手炮","art-perk","传说 神器特性"],
  ["势不可挡火箭发射器","art-perk","传说 神器特性"],
  ["卡德马斯山脊长矛帽","exotic","异域 头盔"],
  ["授权模组：元素充能","art-perk","传说 神器特性"],
  ["授权模组：完全充能","art-perk","传说 神器特性"],
  ["暗影箭矢：狩猎陷阱","el-void","虚空超能 | 光能技能"],
  ["活性放射体液转换器","perk","武器 Perk"],
  ["纯五度\\\\神圣之焰","exotic","异域 Perk"],
  ["能量核心\\\\催化剂","exotic","异域 Perk"],
  ["近战光学瞄准镜：低","perk","武器 Perk"],
  ["近战光学瞄准镜：高","perk","武器 Perk"],
  ["难以逾越的颅骨堡垒","exotic","异域 头盔"],
  ["ACD/0反馈栅","exotic","异域 臂铠"],
  ["亚克兴角战役钻机","exotic","异域 胸部护甲"],
  ["元素能量球：电弧","art-perk","传说 神器特性"],
  ["冲击、震荡、重力","art-perk","传说 神器特性"],
  ["势不可挡斥候步枪","art-perk","传说 神器特性"],
  ["势不可挡狙击步枪","art-perk","传说 神器特性"],
  ["势不可挡脉冲步枪","art-perk","传说 神器特性"],
  ["原始特性专精II","art-perk","传说 神器特性"],
  ["反屏障微型冲锋枪","art-perk","传说 神器特性"],
  ["圣人14号的头盔","exotic","异域 头盔"],
  ["封印阿罕卡拉护手","exotic","异域 臂铠"],
  ["幼年阿罕卡拉之脊","exotic","异域 臂铠"],
  ["强化护盾持续时间","perk","武器 Perk"],
  ["授权模组：回收器","art-perk","传说 神器特性"],
  ["纳米技术追踪导弹","perk","武器 Perk"],
  ["阿尔法·鲁皮之脊","exotic","异域 胸部护甲"],
  ["高强度型弹药储备","perk","武器 Perk"],
  ["IS5环形瞄具","perk","武器 Perk"],
  ["Mk.44让开","exotic","异域 腿部护甲"],
  ["SUROS政权","exotic","异域 自动步枪"],
  ["Suros协同","perk","武器 Perk"],
  ["Veist尖刺","perk","武器 Perk"],
  ["伊邪那岐的重担","exotic","异域 狙击步枪"],
  ["全自动击发系统","perk","武器 Perk"],
  ["冥府三头犬+1","exotic","异域 自动步枪"],
  ["冷冻状态77K","exotic","异域 手枪"],
  ["势不可挡的偃月","art-perk","传说 神器特性"],
  ["势不可挡的手炮","art-perk","传说 神器特性"],
  ["原始特性专精I","art-perk","传说 神器特性"],
  ["反屏障斥候步枪","art-perk","传说 神器特性"],
  ["反屏障狙击步枪","art-perk","传说 神器特性"],
  ["反屏障脉冲步枪","art-perk","传说 神器特性"],
  ["反屏障自动步枪","art-perk","传说 神器特性"],
  ["巴利道斯织怒工","exotic","异域 臂铠"],
  ["强化乙太发生器","art-perk","传说 神器特性"],
  ["快速装弹松身裤","exotic","异域 腿部护甲"],
  ["拉斯普廷军械库","perk","武器 Perk"],
  ["授权模组：手雷","art-perk","传说 神器特性"],
  ["授权模组：电弧","art-perk","传说 神器特性"],
  ["授权模组：缚丝","art-perk","传说 神器特性"],
  ["授权模组：虚空","art-perk","传说 神器特性"],
  ["授权模组：近战","art-perk","传说 神器特性"],
  ["改造版猩红死命","exotic","异域 脉冲步枪"],
  ["新星炸弹：灾变","el-void","虚空超能 | 光能技能"],
  ["普罗米修斯透镜","exotic","异域 追踪步枪"],
  ["沃德克里夫线圈","exotic","异域 火箭发射器"],
  ["特克斯平衡枪托","perk","武器 Perk"],
  ["瞄准自动填装器","art-perk","传说 神器特性"],
  ["罗蕾莱辉煌头盔","exotic","异域 头盔"],
  ["至纯光能护心甲","exotic","异域 胸部护甲"],
  ["被动攻击刀剑格","art-perk","传说 神器特性"],
  ["过载微型冲锋枪","art-perk","传说 神器特性"],
  ["钢铁领主的活力","art-perk","传说 神器特性"],
  ["黄金枪：神枪手","el-solar","烈日超能 | 光能技能"],
  ["黑暗乙太收割者","perk","武器 Perk"],
  ["ATC雷克斯","perk","武器 Perk"],
  ["Vex揭秘者","exotic","异域 融合步枪"],
  ["不稳定神枪手","art-perk","传说 神器特性"],
  ["两次闪电打击","art-perk","传说 神器特性"],
  ["伊卡洛斯握把","perk","武器 Perk"],
  ["伊卡洛斯突进","el-solar","烈日星相"],
  ["传导宇宙水晶","art-perk","传说 神器特性"],
  ["传导宇宙织针","art-perk","传说 神器特性"],
  ["先锋充盈折扣","art-perk","传说 神器特性"],
  ["六翼天使弹药","perk","武器 Perk"],
  ["冰霜-EE5","exotic","异域 腿部护甲"],
  ["刀剑风暴连击","art-perk","传说 神器特性"],
  ["势不可挡勇士","enemy","站内术语"],
  ["势不可挡弓箭","art-perk","传说 神器特性"],
  ["势不可挡手枪","art-perk","传说 神器特性"],
  ["势不可挡手炮","art-perk","传说 神器特性"],
  ["势不可挡融合","art-perk","传说 神器特性"],
  ["升级传感器组","exotic","异域 Perk"],
  ["卡恩斯坦臂章","exotic","异域 臂铠"],
  ["反屏障霰弹枪","art-perk","传说 神器特性"],
  ["吸血鬼的拥抱","exotic","异域 Perk"],
  ["奈扎雷克原罪","exotic","异域 头盔"],
  ["安泰俄斯护盾","exotic","异域 腿部护甲"],
  ["密耳弥冬之触","exotic","异域 Perk"],
  ["小丑皇弹药筒","perk","武器 Perk"],
  ["巴克里斯面具","exotic","异域 头盔"],
  ["引力伏打充能","art-perk","传说 神器特性"],
  ["弹簧荷载悬置","exotic","异域 Perk"],
  ["弹簧钻头弩弹","perk","武器 Perk"],
  ["强化充能时间","perk","武器 Perk"],
  ["强化射弹速度","perk","武器 Perk"],
  ["强化拔枪速度","perk","武器 Perk"],
  ["强化爆炸范围","perk","武器 Perk"],
  ["快速切换枪带","perk","武器 Perk"],
  ["快速精准膛线","art-perk","传说 神器特性"],
  ["感应爆炸飞刀","el-solar","烈日近战"],
  ["战斗和谐护肩","exotic","异域 胸部护甲"],
  ["捕猎者的伏击","el-void","虚空星相"],
  ["新马尔帕伊斯","exotic","异域 脉冲步枪"],
  ["旅行者的选择","exotic","异域 手枪"],
  ["无尽刀剑格挡","perk","武器 Perk"],
  ["曲腹蛛的伪装","exotic","异域 头盔"],
  ["朱雀意图之刃","exotic","异域 偃月"],
  ["机工诡诈臂袖","exotic","异域 臂铠"],
  ["枪管收缩装置","perk","武器 Perk"],
  ["毁灭之牙肩甲","exotic","异域 臂铠"],
  ["汤米的火柴盒","exotic","异域 自动步枪"],
  ["洛伦兹驱动器","exotic","异域 线性融合步枪"],
  ["燃烧步枪弹药","art-perk","传说 神器特性"],
  ["燃烧舞步之道","exotic","异域 腿部护甲"],
  ["玄武行动之刃","exotic","异域 偃月"],
  ["球面序列引信","exotic","异域 Perk"],
  ["神圣黎明之翼","exotic","异域 胸部护甲"],
  ["粘性电浆手雷","el-arc","电弧手雷"],
  ["组合银白利刃","art-perk","传说 神器特性"],
  ["肾上腺素成瘾","perk","武器 Perk"],
  ["能量扩散基质","art-perk","传说 神器特性"],
  ["自动填装枪套","perk","武器 Perk"],
  ["莫比乌斯导管","exotic","异域 Perk"],
  ["虚空武器输能","art-perk","传说 神器特性"],
  ["虚空覆盖护盾","el-void","元素机制"],
  ["覆盖护盾克星","perk","武器 Perk"],
  ["超级杀戮弹匣","perk","武器 Perk"],
  ["辅助弹药储量","perk","武器 Perk"],
  ["过载斥候步枪","art-perk","传说 神器特性"],
  ["过载脉冲步枪","art-perk","传说 神器特性"],
  ["过载自动步枪","art-perk","传说 神器特性"],
  ["过载追踪步枪","art-perk","传说 神器特性"],
  ["重型军械回复","art-perk","传说 神器特性"],
  ["钝器处决弹药","perk","武器 Perk"],
  ["阿克瑞斯传说","exotic","异域 霰弹枪"],
  ["阿斯瑞思之拥","exotic","异域 臂铠"],
  ["阿格尔的权杖","exotic","异域 追踪步枪"],
  ["阿罕卡拉之爪","exotic","异域 臂铠"],
  ["阿罕卡拉之颅","exotic","异域 头盔"],
  ["集中前射火力","art-perk","传说 神器特性"],
  ["雷达增强装置","perk","武器 Perk"],
  ["青龙协同之刃","exotic","异域 偃月"],
  ["非法改装枪套","exotic","异域 Perk"],
  ["风暴舞者之拥","exotic","异域 胸部护甲"],
  ["高密度收束器","perk","武器 Perk"],
  ["三体坐观者","exotic","异域 战斗弓箭"],
  ["不稳定弹药","perk","武器 Perk"],
  ["不稳定流动","art-perk","传说 神器特性"],
  ["丢弃型弹匣","perk","武器 Perk"],
  ["乔木典狱官","exotic","异域 胸部护甲"],
  ["交感军火库","perk","武器 Perk"],
  ["优秀竞争者","perk","武器 Perk"],
  ["元素超充器","art-perk","传说 神器特性"],
  ["光辉跳舞机","exotic","异域 腿部护甲"],
  ["全口径枪膛","perk","武器 Perk"],
  ["决斗者之境","perk","武器 Perk"],
  ["凄凉观察者","el-stasis","冰影星相 / 冰影星相 | 暗影技能"],
  ["凯布利之刺","exotic","异域 臂铠"],
  ["凯布利角盔","exotic","异域 头盔"],
  ["利维坦之息","exotic","异域 战斗弓箭"],
  ["刺激的低语","el-stasis","冰影碎片"],
  ["剑圣刀剑格","perk","武器 Perk"],
  ["加拉尔号角","exotic","异域 火箭发射器"],
  ["加拉诺碎片","exotic","异域 臂铠"],
  ["加速散热器","perk","武器 Perk"],
  ["动态二重奏","exotic","异域 Perk"],
  ["半自动强袭","art-perk","传说 神器特性"],
  ["卡利班之手","exotic","异域 臂铠"],
  ["双子座小丑","exotic","异域 腿部护甲"],
  ["反勇士弹头","art-perk","传说 神器特性"],
  ["反屏障弓箭","art-perk","传说 神器特性"],
  ["反屏障手炮","art-perk","传说 神器特性"],
  ["合成感受器","exotic","异域 臂铠"],
  ["吞噬者之握","exotic","异域 Perk"],
  ["命运的逆转","perk","武器 Perk"],
  ["和平守护者","exotic","异域 腿部护甲"],
  ["噬星者之鳞","exotic","异域 腿部护甲"],
  ["圣人的鼓舞","art-perk","传说 神器特性"],
  ["圣火护心甲","exotic","异域 胸部护甲"],
  ["地磁安定靴","exotic","异域 腿部护甲"],
  ["堕落者日星","exotic","异域 头盔"],
  ["大口径弹药","perk","武器 Perk"],
  ["失重引力子","exotic","异域 头盔"],
  ["奥菲斯钻机","exotic","异域 腿部护甲"],
  ["威胁移除器","perk","武器 Perk"],
  ["嫉妒军械库","perk","武器 Perk"],
  ["守蛾人裹手","exotic","异域 臂铠"],
  ["已回收能量","perk","武器 Perk"],
  ["幸运的一击","perk","武器 Perk"],
  ["幸运覆盆子","exotic","异域 胸部护甲"],
  ["弓手的智谋","perk","武器 Perk"],
  ["引力子尖刺","exotic","异域 手炮"],
  ["引力子长枪","exotic","异域 脉冲步枪"],
  ["弩弹拾荒者","perk","武器 Perk"],
  ["弹跳型弹药","perk","武器 Perk"],
  ["强化冲击力","perk","武器 Perk"],
  ["强化操控性","perk","武器 Perk"],
  ["强化散热器","perk","武器 Perk"],
  ["强化稳定性","perk","武器 Perk"],
  ["忍野的誓言","exotic","异域 臂铠"],
  ["快点SAS","perk","武器 Perk"],
  ["折磨的低语","el-stasis","冰影碎片"],
  ["收割者贡品","perk","武器 Perk"],
  ["改良版瓦解","art-perk","传说 神器特性"],
  ["无情追踪者","exotic","异域 Perk"],
  ["晶体三极管","exotic","异域 Perk"],
  ["晶体转换器","art-perk","传说 神器特性"],
  ["月之阵营靴","exotic","异域 腿部护甲"],
  ["死亡寻觅者","perk","武器 Perk"],
  ["汇编器战靴","exotic","异域 腿部护甲"],
  ["沉默者面具","exotic","异域 头盔"],
  ["没有B计划","exotic","异域 臂铠"],
  ["治疗能量球","art-perk","传说 神器特性"],
  ["法定继承人","exotic","异域 机枪"],
  ["液压推进器","exotic","异域 Perk"],
  ["潇洒行刑者","el-void","虚空星相 / 虚空星相 | 光能技能"],
  ["火风暴臂铠","exotic","异域 臂铠"],
  ["点接触炮架","exotic","异域 臂铠"],
  ["焕光能量球","art-perk","传说 神器特性"],
  ["焚天者誓约","exotic","异域 斥候步枪"],
  ["爆炸波行者","exotic","异域 腿部护甲"],
  ["爆破分配器","perk","武器 Perk"],
  ["爱莲娜之誓","exotic","异域 手炮"],
  ["牵引器火炮","exotic","异域 霰弹枪"],
  ["特里同之罪","exotic","异域 臂铠"],
  ["狙击手冥想","art-perk","传说 神器特性"],
  ["瓦解能量球","art-perk","传说 神器特性"],
  ["电离散热器","perk","武器 Perk"],
  ["盒式呼吸法","perk","武器 Perk"],
  ["眼镜蛇图腾","exotic","异域 Perk"],
  ["瞄准协调器","perk","武器 Perk"],
  ["碎裂能量球","art-perk","传说 神器特性"],
  ["神异量角器","exotic","异域 Perk"],
  ["离心混合器","exotic","异域 自动步枪"],
  ["空气动力学","perk","武器 Perk"],
  ["第二次机会","exotic","异域 臂铠"],
  ["箭头制退器","perk","武器 Perk"],
  ["米达多功能","exotic","异域 斥候步枪"],
  ["紧急信号弹","art-perk","传说 神器特性"],
  ["纪念碑面具","exotic","异域 头盔"],
  ["线性促动器","exotic","异域 Perk"],
  ["终局螺旋钻","exotic","异域 线性融合步枪"],
  ["维王者之剑","exotic","异域 偃月"],
  ["编织者之唤","el-strand","缚丝星相 / 缚丝星相 | 暗影技能"],
  ["羸弱能量球","perk","武器 Perk"],
  ["脆弱的低语","el-stasis","冰影碎片"],
  ["脉冲增幅器","perk","武器 Perk"],
  ["自动填装链","exotic","异域 Perk"],
  ["至高天余烬","el-solar","烈日碎片"],
  ["血红炼金术","exotic","异域 胸部护甲"],
  ["视网膜灼烧","art-perk","传说 神器特性"],
  ["超因果亲和","perk","武器 Perk"],
  ["超因果流体","perk","武器 Perk"],
  ["超频散热器","perk","武器 Perk"],
  ["过载霰弹枪","art-perk","传说 神器特性"],
  ["逃逸艺术家","exotic","异域 臂铠"],
  ["速射HCS","perk","武器 Perk"],
  ["逻辑减速器","art-perk","传说 神器特性"],
  ["邪冬的头盔","exotic","异域 头盔"],
  ["重型刀剑格","perk","武器 Perk"],
  ["锁链的低语","el-stasis","冰影碎片"],
  ["问题解决者","perk","武器 Perk"],
  ["阿莱索尼姆","exotic","异域 榴弹发射器"],
  ["零号世界线","exotic","异域 刀剑"],
  ["雷兽的挽具","exotic","异域 胸部护甲"],
  ["雷达调谐器","perk","武器 Perk"],
  ["霜华窃取者","perk","武器 Perk"],
  ["骗徒的握手","exotic","异域 臂铠"],
  ["鲁扎库之役","exotic","异域 机枪"],
  ["None","perk","武器 Perk"],
  ["一手好牌","art-perk","传说 神器特性"],
  ["万能卡牌","perk","武器 Perk"],
  ["三度迭代","exotic","异域 斥候步枪"],
  ["上升丝线","el-strand","缚丝碎片"],
  ["上行脑路","exotic","异域 Perk"],
  ["不动如山","perk","武器 Perk"],
  ["不屈不挠","perk","武器 Perk"],
  ["不法之徒","perk","武器 Perk"],
  ["不祥之兆","exotic","异域 榴弹发射器"],
  ["专家掌控","art-perk","传说 神器特性"],
  ["专注火花","el-arc","电弧碎片"],
  ["丝线打击","el-strand","缚丝超能 | 暗影技能"],
  ["严冬之怒","el-stasis","冰影超能 | 暗影技能"],
  ["严冬帷幕","el-stasis","冰影星相 / 冰影星相 | 暗影技能"],
  ["严苛光芒","exotic","异域 自动步枪"],
  ["严酷折射","art-perk","传说 神器特性"],
  ["中止之跃","exotic","异域 腿部护甲"],
  ["丰盈满溢","perk","武器 Perk"],
  ["丰足弹药","perk","武器 Perk"],
  ["乘胜追击","art-perk","传说 神器特性"],
  ["事不过四","perk","武器 Perk"],
  ["二元轨道","perk","武器 Perk"],
  ["云霄破击","exotic","异域 狙击步枪"],
  ["互惠拔枪","art-perk","传说 神器特性"],
  ["亡命之徒","perk","武器 Perk"],
  ["亡灵之握","exotic","异域 臂铠"],
  ["亡者传说","exotic","异域 斥候步枪"],
  ["交叉反击","exotic","异域 Perk"],
  ["交换回声","el-void","虚空碎片"],
  ["仁慈余烬","el-solar","烈日碎片"],
  ["从何而来","art-perk","传说 神器特性"],
  ["伏特子弹","perk","武器 Perk"],
  ["伏特火花","el-arc","电弧碎片"],
  ["休止回声","el-void","虚空碎片"],
  ["众神之锤","exotic","异域 Perk"],
  ["传导之吟","el-stasis","冰影碎片"],
  ["传导叉齿","exotic","异域 Perk"],
  ["传说化身","art-perk","传说 神器特性"],
  ["伺机而动","el-void","虚空星相"],
  ["使命琢面","el-prismatic","棱镜碎片"],
  ["保护琢面","el-prismatic","棱镜碎片"],
  ["信标弹药","perk","武器 Perk"],
  ["信标火花","el-arc","电弧碎片"],
  ["修复琢面","el-prismatic","棱镜碎片"],
  ["傀儡操纵","exotic","异域 Perk"],
  ["傻瓜雷达","exotic","异域 头盔"],
  ["元素仁慈","art-perk","传说 神器特性"],
  ["元素电容","perk","武器 Perk"],
  ["元素眩晕","art-perk","传说 神器特性"],
  ["元素磨砺","perk","武器 Perk"],
  ["元素聚合","art-perk","传说 神器特性"],
  ["元素虹吸","art-perk","传说 神器特性"],
  ["元素超驰","art-perk","传说 神器特性"],
  ["充能弩弹","perk","武器 Perk"],
  ["充能火花","el-arc","电弧碎片"],
  ["先知之视","exotic","异域 头盔"],
  ["先锋决心","perk","武器 Perk"],
  ["先锋平反","perk","武器 Perk"],
  ["光中藏弹","perk","武器 Perk"],
  ["光伏镜面","exotic","异域 Perk"],
  ["光子耀斑","art-perk","传说 神器特性"],
  ["光束医师","art-perk","传说 神器特性"],
  ["光照无影","perk","武器 Perk"],
  ["光线余烬","el-solar","烈日碎片"],
  ["光能之触","perk","武器 Perk"],
  ["光能余烬","exotic","异域 Perk"],
  ["光能炮台","perk","武器 Perk"],
  ["光能盛宴","exotic","异域 Perk"],
  ["光辉火花","el-arc","电弧碎片"],
  ["光速拔枪","perk","武器 Perk"],
  ["光铸铅弹","art-perk","传说 神器特性"],
  ["克制破坏","el-void","虚空星相"],
  ["全新招数","exotic","异域 Perk"],
  ["全知之眼","exotic","异域 胸部护甲"],
  ["全面发展","perk","武器 Perk"],
  ["全面提升","perk","武器 Perk"],
  ["全面爆发","exotic","异域 脉冲步枪"],
  ["内爆弹药","perk","武器 Perk"],
  ["再来一份","exotic","异域 Perk"],
  ["冥冥低语","exotic","异域 Perk"],
  ["冥火之刺","exotic","异域 腿部护甲"],
  ["冬日之触","el-stasis","冰影星相"],
  ["冰冷之吟","el-stasis","冰影碎片"],
  ["冰冷伺候","art-perk","传说 神器特性"],
  ["冰冷弹匣","perk","武器 Perk"],
  ["冰川壁垒","exotic","异域 Perk"],
  ["冰川守卫","exotic","异域 Perk"],
  ["冰川手雷","el-stasis","冰影手雷 / 冰影手雷 | 暗影技能"],
  ["冰川收获","el-stasis","冰影星相"],
  ["冰川震击","el-stasis","冰影超能 | 暗影技能"],
  ["冰影碎片","el-stasis","元素机制"],
  ["冰瀑衣钵","exotic","异域 臂铠"],
  ["冰火丝线","art-perk","传说 神器特性"],
  ["冰焰飞弹","el-stasis","冰影星相"],
  ["冰雪之心","exotic","异域 Perk"],
  ["冰霜复兴","art-perk","传说 神器特性"],
  ["冰霜巨人","exotic","异域 融合步枪"],
  ["冰霜护甲","el-stasis","元素机制"],
  ["冰霜脉冲","el-stasis","冰影星相"],
  ["冰霜附体","art-perk","传说 神器特性"],
  ["冲击弹壳","perk","武器 Perk"],
  ["冲击支撑","perk","武器 Perk"],
  ["冲击烈焰","exotic","异域 Perk"],
  ["冲刺之握","perk","武器 Perk"],
  ["冲天枪手","exotic","异域 Perk"],
  ["决心余烬","el-solar","烈日碎片"],
  ["冷冻钢铁","perk","武器 Perk"],
  ["冷却饰物","perk","武器 Perk"],
  ["冷酷收割","el-stasis","冰影星相"],
  ["冷酷无情","exotic","异域 融合步枪"],
  ["凄凉领域","exotic","异域 Perk"],
  ["凉意袭人","art-perk","传说 神器特性"],
  ["凋零游侠","exotic","异域 头盔"],
  ["凌光偏转","exotic","异域 Perk"],
  ["减员激励","perk","武器 Perk"],
  ["凤凰法则","exotic","异域 胸部护甲"],
  ["凶险距离","art-perk","传说 神器特性"],
  ["击倒亡魂","art-perk","传说 神器特性"],
  ["击杀记录","perk","武器 Perk"],
  ["击败他们","el-solar","烈日星相"],
  ["切勿靠近","perk","武器 Perk"],
  ["切换弹匣","perk","武器 Perk"],
  ["切线手雷","el-strand","缚丝手雷"],
  ["创世辉煌","exotic","异域 Perk"],
  ["初级首领","bar-yellow","站内术语"],
  ["利刃耐力","art-perk","传说 神器特性"],
  ["刺客剑刃","perk","武器 Perk"],
  ["刺客野心","perk","武器 Perk"],
  ["刺客风帽","exotic","异域 头盔"],
  ["削弱清敌","art-perk","传说 神器特性"],
  ["剑刃之怒","el-strand","缚丝超能 | 暗影技能"],
  ["割线纤维","exotic","异域 腿部护甲"],
  ["力量增幅","exotic","异域 Perk"],
  ["力量平衡","exotic","异域 腿部护甲"],
  ["加大弹匣","perk","武器 Perk"],
  ["加速突击","perk","武器 Perk"],
  ["加速线圈","perk","武器 Perk"],
  ["务必当心","exotic","异域 Perk"],
  ["劣迹斑斑","perk","武器 Perk"],
  ["动中求存","exotic","异域 Perk"],
  ["动态减摆","perk","武器 Perk"],
  ["动能冲击","art-perk","传说 神器特性"],
  ["动能合成","art-perk","传说 神器特性"],
  ["动能裂口","art-perk","传说 神器特性"],
  ["动能震颤","perk","武器 Perk"],
  ["动量火花","el-arc","电弧碎片"],
  ["势不可挡","perk","武器 Perk"],
  ["勇士之鞭","el-strand","缚丝星相 / 缚丝星相 | 暗影技能"],
  ["勇敢琢面","el-prismatic","棱镜碎片"],
  ["勇气琢面","el-prismatic","棱镜碎片"],
  ["医疗设备","exotic","异域 胸部护甲"],
  ["半影冲击","el-stasis","冰影近战 / 冰影近战 | 暗影技能"],
  ["单人合唱","exotic","异域 自动步枪"],
  ["单人特工","art-perk","传说 神器特性"],
  ["危险临近","exotic","异域 Perk"],
  ["危险区域","perk","武器 Perk"],
  ["危险推力","exotic","异域 胸部护甲"],
  ["即兴弹药","perk","武器 Perk"],
  ["即时打击","perk","武器 Perk"],
  ["厄运号角","exotic","异域 Perk"],
  ["压制偃月","art-perk","传说 神器特性"],
  ["参考框架","perk","武器 Perk"],
  ["双拳紧握","exotic","异域 Perk"],
  ["双重填装","perk","武器 Perk"],
  ["双重闪身","exotic","异域 Perk"],
  ["反制充能","art-perk","传说 神器特性"],
  ["反制能量","art-perk","传说 神器特性"],
  ["反射爆冲","exotic","异域 Perk"],
  ["反转之握","exotic","异域 臂铠"],
  ["反馈火花","el-arc","电弧碎片"],
  ["发热寒颤","art-perk","传说 神器特性"],
  ["受控连射","perk","武器 Perk"],
  ["口袋奇点","el-void","虚空近战 / 虚空近战 | 光能技能"],
  ["古神仪式","art-perk","传说 神器特性"],
  ["各就各位","el-solar","烈日星相"],
  ["合金外壳","perk","武器 Perk"],
  ["合金弹匣","perk","武器 Perk"],
  ["吞食裂缝","exotic","异域 Perk"],
  ["启迪行动","perk","武器 Perk"],
  ["吸吮回声","el-void","虚空碎片"],
  ["吸收电池","exotic","异域 Perk"],
  ["周而复始","perk","武器 Perk"],
  ["命定混沌","exotic","异域 机枪"],
  ["命运眷顾","exotic","异域 腿部护甲"],
  ["咆哮烈焰","el-solar","烈日星相"],
  ["和谐回声","perk","武器 Perk"],
  ["唯我主义","exotic","异域 术士臂环"],
  ["喂食狂热","perk","武器 Perk"],
  ["喷发余烬","el-solar","烈日碎片"],
  ["噩梦激励","exotic","异域 Perk"],
  ["回旋喝彩","exotic","异域 火箭发射器"],
  ["回旋漩涡","el-strand","缚丝星相"],
  ["回火余烬","el-solar","烈日碎片"],
  ["回火刀锋","perk","武器 Perk"],
  ["回转弹药","perk","武器 Perk"],
  ["土卫十三","exotic","异域 融合步枪"],
  ["圣盾强袭","el-void","虚空近战"],
  ["圣盾投掷","el-void","虚空近战 / 虚空近战 | 光能技能"],
  ["地震打击","el-arc","电弧近战"],
  ["坚不可摧","el-void","虚空星相 / 虚空星相 | 光能技能"],
  ["坚定不移","exotic","异域 Perk"],
  ["坚忍克己","exotic","异域 泰坦印记"],
  ["坚韧利刃","perk","武器 Perk"],
  ["坚韧回声","el-void","虚空碎片"],
  ["墓园双星","exotic","异域 微型冲锋枪"],
  ["增幅火花","el-arc","电弧碎片"],
  ["增殖丝线","el-strand","缚丝碎片"],
  ["备用弹匣","perk","武器 Perk"],
  ["复兴之握","exotic","异域 臂铠"],
  ["复苏爆破","art-perk","传说 神器特性"],
  ["外向活泼","perk","武器 Perk"],
  ["多彩虹吸","art-perk","传说 神器特性"],
  ["多杀弹匣","perk","武器 Perk"],
  ["大熊狂怒","exotic","异域 臂铠"],
  ["大肆屠杀","art-perk","传说 神器特性"],
  ["天赋信念","exotic","异域 胸部护甲"],
  ["失时弹匣","perk","武器 Perk"],
  ["失稳回声","el-void","虚空碎片"],
  ["失落之声","exotic","异域 Perk"],
  ["失衡弹药","perk","武器 Perk"],
  ["失调协议","perk","武器 Perk"],
  ["奇点利刃","art-perk","传说 神器特性"],
  ["奉献琢面","el-prismatic","棱镜碎片"],
  ["奋斗串联","perk","武器 Perk"],
  ["如火如荼","exotic","异域 Perk"],
  ["妨害振幅","art-perk","传说 神器特性"],
  ["威胁探测","perk","武器 Perk"],
  ["威能弹药","ammo-heavy","站内术语"],
  ["嫉妒刺客","perk","武器 Perk"],
  ["孤独琢面","el-prismatic","棱镜碎片"],
  ["孤立丝线","el-strand","缚丝碎片"],
  ["宁静一刻","perk","武器 Perk"],
  ["守护丝线","el-strand","缚丝碎片"],
  ["完美浮空","perk","武器 Perk"],
  ["宏伟之嚎","perk","武器 Perk"],
  ["宝藏现世","perk","武器 Perk"],
  ["寒冬之啮","exotic","异域 偃月"],
  ["寒冰断破","el-stasis","冰影星相"],
  ["寒冰核心","exotic","异域 追踪步枪"],
  ["寒脑凝滞","art-perk","传说 神器特性"],
  ["寡妇之丝","el-strand","缚丝星相"],
  ["射击切换","perk","武器 Perk"],
  ["小试牛刀","perk","武器 Perk"],
  ["小队目标","art-perk","传说 神器特性"],
  ["尖刺榴弹","perk","武器 Perk"],
  ["尖锐收割","perk","武器 Perk"],
  ["居合连斩","perk","武器 Perk"],
  ["屏障勇士","enemy","站内术语"],
  ["屏障手雷","exotic","异域 Perk"],
  ["巨脉蜻蜓","perk","武器 Perk"],
  ["巨龙之影","exotic","异域 胸部护甲"],
  ["布瑞遗产","perk","武器 Perk"],
  ["希望琢面","el-prismatic","棱镜碎片"],
  ["帝喾预言","exotic","异域 战斗弓箭"],
  ["帝国效忠","perk","武器 Perk"],
  ["平衡枪托","perk","武器 Perk"],
  ["平衡琢面","el-prismatic","棱镜碎片"],
  ["平顺拔枪","perk","武器 Perk"],
  ["并肩作战","art-perk","传说 神器特性"],
  ["幻金链甲","exotic","异域 Perk"],
  ["广口弹匣","perk","武器 Perk"],
  ["庄家之选","perk","武器 Perk"],
  ["库尔之影","exotic","异域 融合步枪"],
  ["庸人自扰","perk","武器 Perk"],
  ["延时载荷","perk","武器 Perk"],
  ["异星噬菌","exotic","异域 机枪"],
  ["异界之眸","exotic","异域 头盔"],
  ["异端行径","perk","武器 Perk"],
  ["弓手节奏","perk","武器 Perk"],
  ["引爆光束","perk","武器 Perk"],
  ["弱化回声","el-void","虚空碎片"],
  ["弹中藏金","art-perk","传说 神器特性"],
  ["弹性弓弦","perk","武器 Perk"],
  ["弹跳手雷","el-arc","电弧手雷"],
  ["弹道猛击","el-arc","电弧近战"],
  ["强制填装","perk","武器 Perk"],
  ["强力反击","perk","武器 Perk"],
  ["强力首发","perk","武器 Perk"],
  ["强化坚韧","perk","武器 Perk"],
  ["强化填装","perk","武器 Perk"],
  ["强化射程","perk","武器 Perk"],
  ["强化电池","perk","武器 Perk"],
  ["强化精度","perk","武器 Perk"],
  ["彼岸新域","exotic","异域 狙击步枪"],
  ["徒手握把","perk","武器 Perk"],
  ["御寒装备","perk","武器 Perk"],
  ["微型榴弹","perk","武器 Perk"],
  ["心无旁骛","perk","武器 Perk"],
  ["心灵骇入","perk","武器 Perk"],
  ["心纺祷告","el-strand","缚丝星相"],
  ["必然馈赠","exotic","异域 Perk"],
  ["志愿容器","perk","武器 Perk"],
  ["忠诚面具","exotic","异域 头盔"],
  ["快速冲击","art-perk","传说 神器特性"],
  ["快速冷却","exotic","异域 Perk"],
  ["快速启动","perk","武器 Perk"],
  ["快速命中","perk","武器 Perk"],
  ["快速治疗","art-perk","传说 神器特性"],
  ["思维丝线","el-strand","缚丝碎片"],
  ["急冻手雷","el-stasis","冰影手雷 / 冰影手雷 | 暗影技能"],
  ["急切刀锋","perk","武器 Perk"],
  ["急速火花","el-arc","电弧碎片"],
  ["恐惧弥漫","exotic","异域 头盔"],
  ["恐惧面容","exotic","异域 Perk"],
  ["恢复仪式","perk","武器 Perk"],
  ["恩惠琢面","el-prismatic","棱镜碎片"],
  ["恶意抓握","exotic","异域 Perk"],
  ["恶意触碰","exotic","异域 斥候步枪"],
  ["悦耳之声","exotic","异域 线性融合步枪"],
  ["惊奇余烬","el-solar","烈日碎片"],
  ["感应手雷","el-solar","烈日手雷"],
  ["愿望成真","art-perk","传说 神器特性"],
  ["慈悲余烬","el-solar","烈日碎片"],
  ["慷慨琢面","el-prismatic","棱镜碎片"],
  ["我为人人","perk","武器 Perk"],
  ["战争旗帜","el-strand","缚丝星相"],
  ["战嚎炮管","perk","武器 Perk"],
  ["战场检验","perk","武器 Perk"],
  ["战斗人员","enemy","站内术语"],
  ["战斗咆哮","perk","武器 Perk"],
  ["战术弹匣","perk","武器 Perk"],
  ["战栗打击","el-stasis","冰影近战 / 冰影近战 | 暗影技能"],
  ["战锤打击","el-solar","烈日近战 / 烈日近战 | 光能技能"],
  ["戟兵之触","exotic","异域 Perk"],
  ["打烊时间","perk","武器 Perk"],
  ["扩展深渊","art-perk","传说 神器特性"],
  ["扩张回声","el-void","虚空碎片"],
  ["扳机轻语","perk","武器 Perk"],
  ["抑制手雷","el-void","虚空手雷 / 虚空手雷 | 光能技能"],
  ["投掷飞锤","el-solar","烈日近战"],
  ["投身激战","el-strand","缚丝星相"],
  ["抗性火花","el-arc","电弧碎片"],
  ["折角之吟","el-stasis","冰影碎片"],
  ["抚慰余烬","el-solar","烈日碎片"],
  ["护甲充能","armor-charge","站内术语"],
  ["护盾粉碎","art-perk","传说 神器特性"],
  ["报复回声","el-void","虚空碎片"],
  ["持久印象","perk","武器 Perk"],
  ["持久增幅","art-perk","传说 神器特性"],
  ["持续丝线","el-strand","缚丝碎片"],
  ["持续火力","art-perk","传说 神器特性"],
  ["指挥琢面","el-prismatic","棱镜碎片"],
  ["捕网猎手","exotic","异域 Perk"],
  ["掌控全场","perk","武器 Perk"],
  ["收割回声","el-void","虚空碎片"],
  ["放电火花","el-arc","电弧碎片"],
  ["救赎之握","exotic","异域 榴弹发射器"],
  ["散射充能","exotic","异域 Perk"],
  ["散射手雷","el-void","虚空手雷"],
  ["斩首武器","perk","武器 Perk"],
  ["断绝末路","exotic","异域 胸部护甲"],
  ["旋风利刃","perk","武器 Perk"],
  ["无倦利刃","perk","武器 Perk"],
  ["无尽悲痛","perk","武器 Perk"],
  ["无尽渴求","exotic","异域 Perk"],
  ["无形之手","perk","武器 Perk"],
  ["无情打击","perk","武器 Perk"],
  ["无敌索尔","el-solar","烈日星相"],
  ["无时辩解","exotic","异域 脉冲步枪"],
  ["无星暗夜","exotic","异域 Perk"],
  ["无畏充能","perk","武器 Perk"],
  ["无畏护甲","el-arc","电弧星相"],
  ["无知希冀","exotic","异域 臂铠"],
  ["日焰熔炉","exotic","异域 Perk"],
  ["旧神之子","el-void","虚空星相"],
  ["明日之眼","exotic","异域 火箭发射器"],
  ["星云之歌","exotic","异域 头盔"],
  ["星火协议","exotic","异域 胸部护甲"],
  ["星界之火","el-solar","烈日近战"],
  ["星界夜鹰","exotic","异域 头盔"],
  ["显身体验","exotic","异域 Perk"],
  ["晋升振幅","exotic","异域 Perk"],
  ["晨星圣典","exotic","异域 Perk"],
  ["晶石之吟","el-stasis","冰影碎片"],
  ["智慧丝线","el-strand","缚丝碎片"],
  ["暮光军火","el-void","虚空超能 | 光能技能"],
  ["暮域手雷","el-stasis","冰影手雷 / 冰影手雷 | 暗影技能"],
  ["暮域深处","exotic","异域 Perk"],
  ["暴雷之触","el-arc","电弧星相"],
  ["曙光惊喜","perk","武器 Perk"],
  ["最终警告","exotic","异域 手枪"],
  ["最速拔枪","art-perk","传说 神器特性"],
  ["朝向裂口","art-perk","传说 神器特性"],
  ["朦胧回声","el-void","虚空碎片"],
  ["未足之饥","perk","武器 Perk"],
  ["机甲枪套","exotic","异域 Perk"],
  ["杀戮之风","art-perk","传说 神器特性"],
  ["杀戮弹匣","perk","武器 Perk"],
  ["杀手之牙","exotic","异域 霰弹枪"],
  ["权衡飞刀","el-solar","烈日近战"],
  ["束缚丝线","el-strand","缚丝碎片"],
  ["束缚之吟","el-stasis","冰影碎片"],
  ["束缚手雷","el-strand","缚丝手雷 / 缚丝手雷 | 暗影技能"],
  ["条件终局","exotic","异域 霰弹枪"],
  ["极寒凝视","art-perk","传说 神器特性"],
  ["极星长枪","exotic","异域 斥候步枪"],
  ["极限突破","art-perk","传说 神器特性"],
  ["构造收割","el-stasis","冰影星相"],
  ["枪管套筒","perk","武器 Perk"],
  ["枯萎之刃","el-stasis","冰影近战 / 冰影近战 | 暗影技能"],
  ["枯萎凝视","perk","武器 Perk"],
  ["枯萎囤积","exotic","异域 榴弹发射器"],
  ["枯骨鳞片","exotic","异域 微型冲锋枪"],
  ["梦想差事","perk","武器 Perk"],
  ["棱镜转移","art-perk","传说 神器特性"],
  ["椭圆轨道","perk","武器 Perk"],
  ["概率矩阵","exotic","异域 Perk"],
  ["槽化枪管","perk","武器 Perk"],
  ["横断之步","exotic","异域 腿部护甲"],
  ["欣然之速","perk","武器 Perk"],
  ["正义琢面","el-prismatic","棱镜碎片"],
  ["武器大师","perk","武器 Perk"],
  ["死亡之舞","exotic","异域 Perk"],
  ["死亡使者","exotic","异域 火箭发射器"],
  ["死亡信使","exotic","异域 榴弹发射器"],
  ["死守防线","art-perk","传说 神器特性"],
  ["残存回声","el-void","虚空碎片"],
  ["毁灭琢面","el-prismatic","棱镜碎片"],
  ["毁灭雕像","exotic","异域 追踪步枪"],
  ["毒液之触","exotic","异域 Perk"],
  ["毒蛇面貌","exotic","异域 臂铠"],
  ["氦气螺线","exotic","异域 Perk"],
  ["水到渠成","exotic","异域 Perk"],
  ["永动不歇","perk","武器 Perk"],
  ["永劫安泰","exotic","异域 臂铠"],
  ["永劫灵魂","exotic","异域 臂铠"],
  ["永劫雨燕","exotic","异域 臂铠"],
  ["永恒战士","exotic","异域 头盔"],
  ["永恒毁灭","art-perk","传说 神器特性"],
  ["沉默狂啸","el-stasis","冰影超能 | 暗影技能"],
  ["沙丘行者","exotic","异域 腿部护甲"],
  ["沙场备战","perk","武器 Perk"],
  ["治愈手雷","el-solar","烈日手雷 / 烈日手雷 | 光能技能"],
  ["治疗弹匣","perk","武器 Perk"],
  ["泰瑟电触","art-perk","传说 神器特性"],
  ["流动状态","el-arc","电弧星相"],
  ["浮游孢子","exotic","异域 腿部护甲"],
  ["消逝暗影","exotic","异域 Perk"],
  ["涓流充能","perk","武器 Perk"],
  ["涡流手雷","el-void","虚空手雷 / 虚空手雷 | 光能技能"],
  ["涡流电流","perk","武器 Perk"],
  ["深埋血脉","exotic","异域 手枪"],
  ["深度炼金","art-perk","传说 神器特性"],
  ["深海萃取","exotic","异域 Perk"],
  ["混乱无序","exotic","异域 榴弹发射器"],
  ["混合弹匣","perk","武器 Perk"],
  ["混沌交易","exotic","异域 Perk"],
  ["混沌加速","el-void","虚空星相"],
  ["混沌重塑","perk","武器 Perk"],
  ["游荡刺客","exotic","异域 Perk"],
  ["游隼打击","exotic","异域 Perk"],
  ["游隼胫甲","exotic","异域 腿部护甲"],
  ["滑行健射","perk","武器 Perk"],
  ["滑行射击","perk","武器 Perk"],
  ["潜匿弓箭","perk","武器 Perk"],
  ["火力满溢","perk","武器 Perk"],
  ["火炬余烬","el-solar","烈日碎片"],
  ["火焰之触","el-solar","烈日星相"],
  ["火焰润雨","exotic","异域 腿部护甲"],
  ["火焰行者","exotic","异域 Perk"],
  ["火石强袭","art-perk","传说 神器特性"],
  ["火种扳机","art-perk","传说 神器特性"],
  ["火药博弈","el-solar","烈日星相 / 烈日星相 | 光能技能"],
  ["灰烬仪式","exotic","异域 Perk"],
  ["灵魂虹吸","el-void","虚空星相"],
  ["灵魂饮者","perk","武器 Perk"],
  ["灼烧暗影","art-perk","传说 神器特性"],
  ["灾难计划","perk","武器 Perk"],
  ["炎阳护腕","exotic","异域 臂铠"],
  ["炙热升腾","el-solar","烈日星相"],
  ["炼金蚀刻","exotic","异域 Perk"],
  ["炽热余烬","el-solar","烈日碎片"],
  ["烈日壁垒","exotic","异域 Perk"],
  ["烈日弹丸","exotic","异域 手炮"],
  ["烈日手雷","el-solar","烈日手雷"],
  ["烈日爆发","art-perk","传说 神器特性"],
  ["烈焰之心","art-perk","传说 神器特性"],
  ["烈焰之歌","el-solar","烈日超能 | 光能技能"],
  ["烈焰战锤","el-solar","烈日超能 | 光能技能"],
  ["烈焰手雷","el-solar","烈日手雷"],
  ["烈焰烧灼","exotic","异域 Perk"],
  ["烤焦他们","exotic","异域 Perk"],
  ["烧焦余烬","el-solar","烈日碎片"],
  ["热力四射","perk","武器 Perk"],
  ["热情急冻","exotic","异域 Perk"],
  ["热能雾化","perk","武器 Perk"],
  ["热血上头","perk","武器 Perk"],
  ["焕光碎片","art-perk","传说 神器特性"],
  ["焚烧响指","el-solar","烈日近战 / 烈日近战 | 光能技能"],
  ["焦燃余烬","el-solar","烈日碎片"],
  ["煅炉眷属","perk","武器 Perk"],
  ["熔岩激涌","perk","武器 Perk"],
  ["燃烧之拳","exotic","异域 Perk"],
  ["燃烧之魂","exotic","异域 Perk"],
  ["燃烧余烬","el-solar","烈日碎片"],
  ["燃烧手雷","el-solar","烈日手雷"],
  ["燃烧野心","perk","武器 Perk"],
  ["爆炸光能","perk","武器 Perk"],
  ["爆炸协议","perk","武器 Perk"],
  ["爆炸弩弹","perk","武器 Perk"],
  ["爆炸箭头","perk","武器 Perk"],
  ["爆破专家","perk","武器 Perk"],
  ["爆破之构","perk","武器 Perk"],
  ["特技专注","exotic","异域 Perk"],
  ["特殊弹药","ammo-special","站内术语"],
  ["牺牲琢面","el-prismatic","棱镜碎片"],
  ["狂怒丝线","el-strand","缚丝碎片"],
  ["狂怒导体","exotic","异域 Perk"],
  ["狂暴利刃","el-strand","缚丝近战 / 缚丝近战 | 暗影技能"],
  ["狂暴饥饿","art-perk","传说 神器特性"],
  ["狡诈严冬","exotic","异域 臂铠"],
  ["独眼面具","exotic","异域 头盔"],
  ["狭窄视野","perk","武器 Perk"],
  ["猖獗雄狮","exotic","异域 腿部护甲"],
  ["珍贵伤痕","exotic","异域 头盔"],
  ["球形闪电","el-arc","电弧近战"],
  ["瓦解破裂","perk","武器 Perk"],
  ["生命源泉","exotic","异域 Perk"],
  ["生命轮回","perk","武器 Perk"],
  ["生成丝线","el-strand","缚丝碎片"],
  ["生物强化","exotic","异域 Perk"],
  ["电光充能","el-arc","元素机制"],
  ["电光手雷","el-arc","电弧手雷 / 电弧手雷 | 光能技能"],
  ["电弧之魂","el-arc","电弧星相"],
  ["电弧复合","art-perk","传说 神器特性"],
  ["电荷思维","el-arc","电弧星相"],
  ["痛苦之道","perk","武器 Perk"],
  ["白霜-Z","exotic","异域 胸部护甲"],
  ["盈溢光能","exotic","异域 Perk"],
  ["盘蛇苞片","exotic","异域 胸部护甲"],
  ["目标锁定","perk","武器 Perk"],
  ["直击要害","perk","武器 Perk"],
  ["直觉火花","el-arc","电弧碎片"],
  ["相位弹匣","perk","武器 Perk"],
  ["相对主义","exotic","异域 猎人披风"],
  ["盾牌迷途","perk","武器 Perk"],
  ["真理之容","exotic","异域 头盔"],
  ["真血之法","exotic","异域 Perk"],
  ["眩晕恢复","perk","武器 Perk"],
  ["眩晕融合","art-perk","传说 神器特性"],
  ["眩晕装弹","perk","武器 Perk"],
  ["睡者之吼","exotic","异域 线性融合步枪"],
  ["督军印记","exotic","异域 Perk"],
  ["瞬变风暴","exotic","异域 自动步枪"],
  ["矛隼胸甲","exotic","异域 胸部护甲"],
  ["砥砺刀锋","perk","武器 Perk"],
  ["破碎之吟","el-stasis","冰影碎片"],
  ["破碎俯冲","el-stasis","冰影星相"],
  ["碎盾弹药","art-perk","传说 神器特性"],
  ["碎裂利刃","perk","武器 Perk"],
  ["碎裂手雷","el-stasis","冰影手雷"],
  ["磁性手雷","el-void","虚空手雷 / 虚空手雷 | 光能技能"],
  ["祝福琢面","el-prismatic","棱镜碎片"],
  ["神化面纱","exotic","异域 头盔"],
  ["神圣献祭","el-solar","烈日星相 / 烈日星相 | 光能技能"],
  ["神圣裁决","exotic","异域 追踪步枪"],
  ["神秘织针","el-strand","缚丝近战 | 暗影技能"],
  ["神龙利爪","exotic","异域 Perk"],
  ["神龙利齿","exotic","异域 Perk"],
  ["祭官折扣","art-perk","传说 神器特性"],
  ["禅意时刻","perk","武器 Perk"],
  ["离别赠礼","exotic","异域 Perk"],
  ["离子哨兵","el-arc","电弧星相"],
  ["离子导体","exotic","异域 Perk"],
  ["离子火花","el-arc","电弧碎片"],
  ["离子电池","perk","武器 Perk"],
  ["离子轨迹","el-arc","元素机制"],
  ["秩序祝福","exotic","异域 Perk"],
  ["移动目标","perk","武器 Perk"],
  ["稳健之手","perk","武器 Perk"],
  ["稳若磐石","perk","武器 Perk"],
  ["空中扳机","perk","武器 Perk"],
  ["空中袭击","perk","武器 Perk"],
  ["穿透手枪","art-perk","传说 神器特性"],
  ["突击屏障","exotic","异域 Perk"],
  ["突击弹匣","perk","武器 Perk"],
  ["突触接合","exotic","异域 Perk"],
  ["第六郊狼","exotic","异域 胸部护甲"],
  ["第四骑士","exotic","异域 霰弹枪"],
  ["第四魔法","exotic","异域 Perk"],
  ["粒子重建","art-perk","传说 神器特性"],
  ["粘性榴弹","perk","武器 Perk"],
  ["粘附弹药","perk","武器 Perk"],
  ["精准命中","stack","站内术语"],
  ["精准射线","art-perk","传说 神器特性"],
  ["精准工具","perk","武器 Perk"],
  ["精准平等","art-perk","传说 神器特性"],
  ["精准连击","perk","武器 Perk"],
  ["精巧箭杆","perk","武器 Perk"],
  ["精确弹药","perk","武器 Perk"],
  ["精细调整","perk","武器 Perk"],
  ["精致坟墓","exotic","异域 融合步枪"],
  ["糖果生意","exotic","异域 自动步枪"],
  ["紧密编织","art-perk","传说 神器特性"],
  ["紧逼近战","perk","武器 Perk"],
  ["纠缠罗网","art-perk","传说 神器特性"],
  ["纳米弹药","perk","武器 Perk"],
  ["线织尖刺","el-strand","缚丝近战 / 缚丝近战 | 暗影技能"],
  ["线织幽灵","el-strand","缚丝星相 / 缚丝星相 | 暗影技能"],
  ["线织爆破","art-perk","传说 神器特性"],
  ["线虫手雷","el-strand","缚丝手雷 / 缚丝手雷 | 暗影技能"],
  ["线虫繁殖","art-perk","传说 神器特性"],
  ["组合打击","el-arc","电弧近战 / 电弧近战 | 光能技能"],
  ["细分曲面","exotic","异域 融合步枪"],
  ["织造铠甲","el-strand","元素机制"],
  ["织针风暴","el-strand","缚丝超能 | 暗影技能"],
  ["终局丝线","el-strand","缚丝碎片"],
  ["结晶残花","perk","武器 Perk"],
  ["绝路专注","perk","武器 Perk"],
  ["统御琢面","el-prismatic","棱镜碎片"],
  ["维度偏移","perk","武器 Perk"],
  ["维持生计","perk","武器 Perk"],
  ["编织微步","el-strand","缚丝星相"],
  ["缚丝士兵","art-perk","传说 神器特性"],
  ["置身其中","art-perk","传说 神器特性"],
  ["群敌飞梭","art-perk","传说 神器特性"],
  ["老兵睿智","perk","武器 Perk"],
  ["耐久之吟","el-stasis","冰影碎片"],
  ["聚合充能","perk","武器 Perk"],
  ["聚焦狂怒","perk","武器 Perk"],
  ["能量加速","art-perk","传说 神器特性"],
  ["能量转换","perk","武器 Perk"],
  ["脆弱专注","perk","武器 Perk"],
  ["脉冲手雷","el-arc","电弧手雷 / 电弧手雷 | 光能技能"],
  ["脉搏监控","perk","武器 Perk"],
  ["腐臭弹药","perk","武器 Perk"],
  ["腰射握把","perk","武器 Perk"],
  ["腹背受敌","perk","武器 Perk"],
  ["致命失误","perk","武器 Perk"],
  ["致命电流","el-arc","电弧星相"],
  ["致盲震颤","art-perk","传说 神器特性"],
  ["花招戏法","perk","武器 Perk"],
  ["苍白苏醒","exotic","异域 臂铠"],
  ["苦涩怨恨","perk","武器 Perk"],
  ["苦痛之力","art-perk","传说 神器特性"],
  ["英勇利刃","exotic","异域 刀剑"],
  ["英勇礼服","exotic","异域 胸部护甲"],
  ["英勇跃升","exotic","异域 Perk"],
  ["荣耀冲锋","exotic","异域 Perk"],
  ["荣耀琢面","el-prismatic","棱镜碎片"],
  ["蒙特卡洛","exotic","异域 自动步枪"],
  ["蔷薇束缚","exotic","异域 臂铠"],
  ["藏匿之狼","perk","武器 Perk"],
  ["虚无镣铐","exotic","异域 臂铠"],
  ["虚空供养","el-void","虚空星相 / 虚空星相 | 光能技能"],
  ["虚空助焊","art-perk","传说 神器特性"],
  ["虚空墙壁","el-void","虚空手雷"],
  ["虚空复兴","art-perk","传说 神器特性"],
  ["虚空尖刺","el-void","虚空手雷"],
  ["虚空感染","art-perk","传说 神器特性"],
  ["虚空裂口","el-void","元素机制"],
  ["虚空附体","exotic","异域 Perk"],
  ["虚空霸权","art-perk","传说 神器特性"],
  ["虚荣自负","exotic","异域 胸部护甲"],
  ["虫神爱抚","exotic","异域 臂铠"],
  ["虫骸头冠","exotic","异域 头盔"],
  ["蜂群手雷","el-solar","烈日手雷 / 烈日手雷 | 光能技能"],
  ["蜕变丝线","el-strand","缚丝碎片"],
  ["蜡烛PS","perk","武器 Perk"],
  ["融合手雷","el-solar","烈日手雷"],
  ["融合掌控","exotic","异域 Perk"],
  ["蠕虫低语","exotic","异域 狙击步枪"],
  ["血色浪漫","exotic","异域 手炮"],
  ["行星洪流","exotic","异域 Perk"],
  ["补能回声","el-void","虚空碎片"],
  ["补血矩阵","exotic","异域 Perk"],
  ["补足神盾","perk","武器 Perk"],
  ["裂空打击","el-arc","电弧星相"],
  ["裂解之吟","el-stasis","冰影碎片"],
  ["裂隙之吟","el-stasis","冰影碎片"],
  ["西坦壁垒","exotic","异域 臂铠"],
  ["覆盖护盾","pickup","元素机制"],
  ["觉醒琢面","el-prismatic","棱镜碎片"],
  ["警惕回声","el-void","虚空碎片"],
  ["警惕羽翼","exotic","异域 脉冲步枪"],
  ["诡异箭矢","exotic","异域 Perk"],
  ["详尽研究","perk","武器 Perk"],
  ["诱导推销","perk","武器 Perk"],
  ["诱捕猛击","el-strand","缚丝星相"],
  ["赋能信标","exotic","异域 Perk"],
  ["起泡余烬","el-solar","烈日碎片"],
  ["超充弹匣","perk","武器 Perk"],
  ["超凡时刻","perk","武器 Perk"],
  ["超越遮罩","exotic","异域 Perk"],
  ["超轻导轨","perk","武器 Perk"],
  ["超载手炮","art-perk","传说 神器特性"],
  ["超载手雷","art-perk","传说 神器特性"],
  ["超频上膛","art-perk","传说 神器特性"],
  ["越战越勇","perk","武器 Perk"],
  ["跳跃喷射","exotic","异域 Perk"],
  ["轨迹证据","art-perk","传说 神器特性"],
  ["轻捷脚步","perk","武器 Perk"],
  ["轻质飞刀","el-solar","烈日近战"],
  ["辅助炸药","perk","武器 Perk"],
  ["辉耀炽热","perk","武器 Perk"],
  ["辐径晚星","exotic","异域 胸部护甲"],
  ["边打边劫","perk","武器 Perk"],
  ["边打边跑","perk","武器 Perk"],
  ["过充武器","art-perk","传说 神器特性"],
  ["过载刀剑","art-perk","传说 神器特性"],
  ["过载勇士","enemy","站内术语"],
  ["过载机枪","art-perk","传说 神器特性"],
  ["过载速射","art-perk","传说 神器特性"],
  ["迎接风暴","art-perk","传说 神器特性"],
  ["近战动量","perk","武器 Perk"],
  ["近接能量","perk","武器 Perk"],
  ["还治彼身","perk","武器 Perk"],
  ["进化丝线","el-strand","缚丝碎片"],
  ["进攻堡垒","el-void","虚空星相"],
  ["远方砖块","art-perk","传说 神器特性"],
  ["远距填装","art-perk","传说 神器特性"],
  ["违抗琢面","el-prismatic","棱镜碎片"],
  ["连锁反应","perk","武器 Perk"],
  ["连锁闪电","el-arc","电弧近战 / 电弧近战 | 光能技能"],
  ["迷失一击","el-arc","电弧近战"],
  ["迷失手雷","perk","武器 Perk"],
  ["迷惑爆发","perk","武器 Perk"],
  ["追踪模块","perk","武器 Perk"],
  ["适配弹药","perk","武器 Perk"],
  ["逆转之吟","el-stasis","冰影碎片"],
  ["逝者留痕","exotic","异域 Perk"],
  ["速射瞄准","perk","武器 Perk"],
  ["速射神枪","el-solar","烈日星相"],
  ["逼入绝境","perk","武器 Perk"],
  ["遁形处决","exotic","异域 Perk"],
  ["邪剑守则","perk","武器 Perk"],
  ["邪恶工具","exotic","异域 斥候步枪"],
  ["邪恶收割","art-perk","传说 神器特性"],
  ["邪恶符咒","exotic","异域 脉冲步枪"],
  ["邪恶编织","art-perk","传说 神器特性"],
  ["醒神丝线","art-perk","传说 神器特性"],
  ["重型弩弹","perk","武器 Perk"],
  ["重新调度","perk","武器 Perk"],
  ["重生丝线","el-strand","缚丝碎片"],
  ["量子光束","el-void","虚空手雷"],
  ["量级火花","el-arc","电弧碎片"],
  ["金中藏弹","perk","武器 Perk"],
  ["金刚扣钩","exotic","异域 Perk"],
  ["钢铁之触","perk","武器 Perk"],
  ["钢铁凝视","perk","武器 Perk"],
  ["钢铁握把","perk","武器 Perk"],
  ["钻石长矛","el-stasis","冰影星相 / 冰影星相 | 暗影技能"],
  ["铝热手雷","el-solar","烈日手雷 / 烈日手雷 | 光能技能"],
  ["铤而走险","perk","武器 Perk"],
  ["银白利刃","art-perk","传说 神器特性"],
  ["银白箭袋","art-perk","传说 神器特性"],
  ["银白重炮","art-perk","传说 神器特性"],
  ["锇素手套","exotic","异域 臂铠"],
  ["锋利棱角","exotic","异域 Perk"],
  ["锤子敲钉","perk","武器 Perk"],
  ["锯齿刀锋","perk","武器 Perk"],
  ["锯齿弩弹","perk","武器 Perk"],
  ["锻造大师","exotic","异域 Perk"],
  ["锻造膛线","perk","武器 Perk"],
  ["镖弹风暴","el-strand","缚丝星相"],
  ["长矛警戒","exotic","异域 Perk"],
  ["闪光手雷","el-arc","电弧手雷"],
  ["闪电反击","perk","武器 Perk"],
  ["闪电手雷","el-arc","电弧手雷"],
  ["闪电激涌","el-arc","电弧星相 / 电弧星相 | 光能技能"],
  ["闪电过载","art-perk","传说 神器特性"],
  ["防护裂口","art-perk","传说 神器特性"],
  ["附加弹匣","perk","武器 Perk"],
  ["陆地坦克","perk","武器 Perk"],
  ["除颤爆破","art-perk","传说 神器特性"],
  ["陨星胸甲","exotic","异域 胸部护甲"],
  ["陷阱炸弹","el-void","虚空近战 / 虚空近战 | 光能技能"],
  ["隐秘追猎","exotic","异域 狙击步枪"],
  ["隐身步法","el-void","虚空星相"],
  ["集体义务","exotic","异域 脉冲步枪"],
  ["集体使命","perk","武器 Perk"],
  ["集体拳击","perk","武器 Perk"],
  ["集体爆破","perk","武器 Perk"],
  ["集体行动","perk","武器 Perk"],
  ["集束炸弹","perk","武器 Perk"],
  ["集群战术","art-perk","传说 神器特性"],
  ["雨淞弧线","exotic","异域 战斗弓箭"],
  ["雪上加霜","perk","武器 Perk"],
  ["零号修订","exotic","异域 脉冲步枪"],
  ["雷电通流","exotic","异域 胸部护甲"],
  ["雷霆一击","el-arc","电弧近战 / 电弧近战 | 光能技能"],
  ["雷霆万钧","el-arc","电弧超能 | 光能技能"],
  ["雷霆冲击","el-arc","电弧超能 | 光能技能"],
  ["雷霆反击","art-perk","传说 神器特性"],
  ["需求层级","exotic","异域 战斗弓箭"],
  ["震慑行动","art-perk","传说 神器特性"],
  ["震颤反馈","perk","武器 Perk"],
  ["震颤火花","el-arc","电弧碎片"],
  ["霜袍服装","exotic","异域 胸部护甲"],
  ["霸道回声","el-void","虚空碎片"],
  ["静铃无响","art-perk","传说 神器特性"],
  ["韵律之吟","el-stasis","冰影碎片"],
  ["顺畅换弹","perk","武器 Perk"],
  ["领主之末","exotic","异域 Perk"],
  ["领事投掷","exotic","异域 Perk"],
  ["频率火花","el-arc","电弧碎片"],
  ["风冷核心","perk","武器 Perk"],
  ["风暴之眼","perk","武器 Perk"],
  ["风暴头冠","exotic","异域 头盔"],
  ["风暴怒吼","el-stasis","冰影星相"],
  ["风暴手雷","el-arc","电弧手雷 / 电弧手雷 | 光能技能"],
  ["风暴涌动","perk","武器 Perk"],
  ["风暴要塞","el-arc","电弧星相"],
  ["风暴边缘","el-arc","电弧超能 | 光能技能"],
  ["飞刀戏法","el-solar","烈日近战 / 烈日近战 | 光能技能"],
  ["飞掠尖刺","exotic","异域 Perk"],
  ["飞翼日蚀","exotic","异域 Perk"],
  ["饥渴刀锋","perk","武器 Perk"],
  ["饥饿之吟","el-stasis","冰影碎片"],
  ["饥饿回声","el-void","虚空碎片"],
  ["驱逐回声","el-void","虚空碎片"],
  ["骨灰余烬","el-solar","烈日碎片"],
  ["高优先级","exotic","异域 Perk"],
  ["高尚事迹","perk","武器 Perk"],
  ["高爆弹药","perk","武器 Perk"],
  ["高爆载荷","perk","武器 Perk"],
  ["高级反射","perk","武器 Perk"],
  ["高速发射","perk","武器 Perk"],
  ["高速弹药","perk","武器 Perk"],
  ["鬼灵激涌","el-void","虚空近战"],
  ["鬼神胸甲","exotic","异域 胸部护甲"],
  ["魔鬼之厄","exotic","异域 手枪"],
  ["鲜弹芬芳","art-perk","传说 神器特性"],
  ["鹰眼骇客","exotic","异域 Perk"],
  ["黄金三角","perk","武器 Perk"],
  ["黎明副歌","exotic","异域 头盔"],
  ["黎明琢面","el-prismatic","棱镜碎片"],
  ["黏附冲击","art-perk","传说 神器特性"],
  ["黑色利爪","exotic","异域 刀剑"],
  ["龙之复仇","perk","武器 Perk"],
  ["B计划","perk","武器 Perk"],
  ["不稳定","deb-void","元素机制"],
  ["二象性","exotic","异域 霰弹枪"],
  ["传家宝","exotic","异域 战斗弓箭"],
  ["先驱者","exotic","异域 手枪"],
  ["光抑制","perk","武器 Perk"],
  ["光膛枪","perk","武器 Perk"],
  ["入侵者","exotic","异域 手枪"],
  ["全明星","perk","武器 Perk"],
  ["剪刀指","exotic","异域 Perk"],
  ["勘探者","exotic","异域 榴弹发射器"],
  ["北极光","exotic","异域 狙击步枪"],
  ["北极星","exotic","异域 追踪步枪"],
  ["双尾狐","exotic","异域 火箭发射器"],
  ["双脚架","perk","武器 Perk"],
  ["右勾拳","perk","武器 Perk"],
  ["地狱火","el-solar","烈日星相 / 烈日星相 | 光能技能"],
  ["大合奏","perk","武器 Perk"],
  ["大序曲","exotic","异域 机枪"],
  ["守愿者","exotic","异域 战斗弓箭"],
  ["守护者","bar-orange","站内术语"],
  ["守誓者","exotic","异域 臂铠"],
  ["寄生虫","exotic","异域 榴弹发射器"],
  ["帝王蝶","exotic","异域 战斗弓箭"],
  ["幸运裤","exotic","异域 腿部护甲"],
  ["弑后者","exotic","异域 线性融合步枪"],
  ["弱化波","art-perk","传说 神器特性"],
  ["弹药带","perk","武器 Perk"],
  ["战略家","perk","武器 Perk"],
  ["投弹手","exotic","异域 腿部护甲"],
  ["护甲匠","art-perk","传说 神器特性"],
  ["拳击手","perk","武器 Perk"],
  ["搜索队","perk","武器 Perk"],
  ["摩伊拉","exotic","异域 胸部护甲"],
  ["故我在","exotic","异域 刀剑"],
  ["斗剑士","perk","武器 Perk"],
  ["施法者","enemy","站内术语"],
  ["杀人风","perk","武器 Perk"],
  ["法夫纳","exotic","异域 线性融合步枪"],
  ["注意了","perk","武器 Perk"],
  ["泰拉巴","exotic","异域 微型冲锋枪"],
  ["测距仪","perk","武器 Perk"],
  ["热切换","perk","武器 Perk"],
  ["生命值","health","站内术语"],
  ["电介质","art-perk","传说 神器特性"],
  ["监护人","exotic","异域 霰弹枪"],
  ["盗墓者","perk","武器 Perk"],
  ["破冰者","exotic","异域 狙击步枪"],
  ["碎愿者","exotic","异域 战斗弓箭"],
  ["穿甲弹","perk","武器 Perk"],
  ["级联点","perk","武器 Perk"],
  ["终结技","enemy","站内术语"],
  ["群居者","exotic","异域 榴弹发射器"],
  ["能量球","orb","站内术语"],
  ["萤火虫","perk","武器 Perk"],
  ["裂波者","exotic","异域 追踪步枪"],
  ["觅敌者","exotic","异域 头盔"],
  ["赴险者","exotic","异域 微型冲锋枪"],
  ["超新星","art-perk","传说 神器特性"],
  ["踢踏5","exotic","异域 腿部护甲"],
  ["重力井","perk","武器 Perk"],
  ["防抖动","perk","武器 Perk"],
  ["阻止力","perk","武器 Perk"],
  ["零因子","exotic","异域 Perk"],
  ["领航员","exotic","异域 追踪步枪"],
  ["黑桃A","exotic","异域 手炮"],
  ["龙之啮","art-perk","传说 神器特性"],
  ["仁心","exotic","异域 臂铠"],
  ["冰影","el-stasis","元素机制"],
  ["冰柱","art-perk","传说 神器特性"],
  ["冻结","deb-stasis","元素机制"],
  ["减益","debuff","站内术语"],
  ["减速","deb-stasis","元素机制"],
  ["凤巢","exotic","异域 腿部护甲"],
  ["割裂","deb-strand","元素机制"],
  ["动能","el-kinetic","元素机制"],
  ["劲弩","exotic","异域 线性融合步枪"],
  ["千语","exotic","异域 融合步枪"],
  ["压制","deb-void","元素机制"],
  ["叛贼","exotic","异域 手炮"],
  ["吞食","el-void","元素机制"],
  ["坏疽","exotic","异域 自动步枪"],
  ["增幅","el-arc","元素机制"],
  ["增益","buff","站内术语"],
  ["奋发","exotic","异域 Perk"],
  ["崩解","art-perk","传说 神器特性"],
  ["异域","exotic","站内术语"],
  ["心影","exotic","异域 刀剑"],
  ["悬停","deb-strand","元素机制"],
  ["战心","exotic","异域 Perk"],
  ["战狮","exotic","异域 榴弹发射器"],
  ["抓钩","el-strand","缚丝手雷 / 缚丝手雷 | 暗影技能"],
  ["挽歌","exotic","异域 刀剑"],
  ["据点","exotic","异域 臂铠"],
  ["棱镜","el-prismatic","元素机制"],
  ["橙血","bar-orange","站内术语"],
  ["治愈","el-solar","元素机制"],
  ["流明","exotic","异域 手炮"],
  ["渎职","exotic","异域 手炮"],
  ["火炬","art-perk","传说 神器特性"],
  ["灼烧","deb-solar","元素机制"],
  ["炫火","exotic","异域 胸部护甲"],
  ["点燃","deb-solar","元素机制"],
  ["烈日","el-solar","元素机制"],
  ["焕光","el-solar","元素机制"],
  ["焰灵","el-solar","元素机制"],
  ["熊卫","exotic","异域 Perk"],
  ["狂飙","exotic","异域 手炮"],
  ["狼毒","exotic","异域 刀剑"],
  ["狼王","exotic","异域 霰弹枪"],
  ["玄铠","exotic","异域 臂铠"],
  ["玉兔","exotic","异域 斥候步枪"],
  ["瓦解","deb-strand","元素机制"],
  ["电弧","el-arc","元素机制"],
  ["盾爆","el-solar","烈日星相"],
  ["真相","exotic","异域 火箭发射器"],
  ["碎裂","deb-stasis","元素机制"],
  ["紧身","exotic","异域 Perk"],
  ["红血","bar-red","站内术语"],
  ["缚丝","el-strand","元素机制"],
  ["缠结","el-strand","元素机制"],
  ["缩影","exotic","异域 追踪步枪"],
  ["羁客","el-strand","缚丝星相"],
  ["自己","enemy","站内术语"],
  ["致盲","deb-arc","元素机制"],
  ["荆棘","exotic","异域 手炮"],
  ["虚弱","deb-void","元素机制"],
  ["虚空","el-void","元素机制"],
  ["蝎狮","exotic","异域 微型冲锋枪"],
  ["超凡","el-prismatic","元素机制"],
  ["越橘","exotic","异域 微型冲锋枪"],
  ["还击","art-perk","传说 神器特性"],
  ["遗言","exotic","异域 手炮"],
  ["金缮","exotic","异域 Perk"],
  ["针术","exotic","异域 Perk"],
  ["隐身","el-void","元素机制"],
  ["隼月","exotic","异域 手炮"],
  ["雄鹿","exotic","异域 头盔"],
  ["雷神","exotic","异域 机枪"],
  ["震颤","deb-arc","元素机制"],
  ["风寒","art-perk","传说 神器特性"],
  ["飞升","el-arc","电弧星相 / 电弧星相 | 光能技能"],
  ["首领","bar-yellow","站内术语"],
  ["鼠王","exotic","异域 手枪"],
  ["龙息","exotic","异域 火箭发射器"],
]}
